### ISSUE TITLE
能提供部署详细一点的文档，或者图片吗，部署有点问题呀！

### ISSUE THREAD

**Issue by lzx13080010188** [IndustryEssentials/ymir#1036]

**Comment by phoenix-xhuang** [comment]
具体是遇到什么问题？

**Comment by wangxy-hub** [comment]
docker拉取镜像一直失败
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"industryessentials/executor-det-yolov4-training","Action":"pull"}]}]}

**Comment by phoenix-xhuang** [comment]
直接运行docker pull industryessentials/executor-det-yolov4-training成功吗？
这些镜像是在dockerhub的公共空间，不需要登陆验证的，你们是否有使用private docker registry？

**Comment by lzx13080010188** [comment]
第一次启动，lable-free，没有选择None，之后一直启动失败

**Comment by lzx13080010188** [comment]
readme中部署方面可以写详细一点吗？这样就可以好排查了

**Comment by lzx13080010188** [comment]
label-free这个直接docker-compose部署吗？我看readme文档没有详细说明

**Comment by Zhang-SJ930104** [comment]
你启动ymir.sh脚本，选择了label free之后应该会提示您没有配置host吧。
readme文档有告诉您如何配置标注对应的host
![image](https://user-images.githubusercontent.com/91466580/185075232-4217f8c9-e0fb-4471-a093-dd9fc399e060.png)

**Comment by lzx13080010188** [comment]
我第二次启动ymir.sh，什么都没有提示了，直接启动失败，其实我不想配置label free，第二次启动没有提示选择label-free的这种提示，直接失败

**Comment by Zhang-SJ930104** [comment]
您将.env文件里面的LABEL_TOOL的配置清空一下。然后再启动ymir.sh脚本就会重新询问你使用什么标注工具了

**Comment by lzx13080010188** [comment]
感谢！就是要这个回答
