### ISSUE TITLE
GUI运行训练模型时，报错permission denied nvidia-docker

### ISSUE THREAD

**Issue by YiqinXu** [IndustryEssentials/ymir#1060]
如题，
按GUI部署步骤部署好后，web端能正常访问，数据集也可以成功导入。
但是开始训练模型时，提示失败，查看日志显示报错， permission denied nvidia-docker是什么原因呢。
报错如图所示，
![2AQgvPcwyV](https://user-images.githubusercontent.com/44312441/185084144-c583c53c-887c-4523-b1a5-0bac5da07d9f.jpg)

另外，
1. 新版本docker中，其实不用nvidia-docker命令了，用的是docker run --gpus all，目前该项目不支持这种模式吗？
2. 程序运行时，好像默认是用root用户，包括新建的文件夹写的日志啥的，都是root的，能否设置成为使用当前用户运行呢？
3. 我怎么导入自己的docker镜像到项目中呢，帮助文档里暂时没有找到相关的介绍。

谢谢

**Comment by fenrir-z** [comment]
1. 看起来 nvidia-docker 没有执行权限
2. 现在并没有提供 docker run --gpus all 模式
3. 现在后台运行时，只能使用 root 权限运行
4. 有两篇文档可以满足你的要求，一个是 https://github.com/IndustryEssentials/ymir/blob/master/docs/ymir-cmd-container.md，另一个是 https://github.com/IndustryEssentials/ymir/tree/master/docker_executor/sample_executor

**Comment by YiqinXu** [comment]
我的系统没有装nvidia-docker，照理说报错应该是报command not found才对，但是上来就报没有权限...
不知道我装一个nvidia-docker能不能解决问题

**Comment by fenrir-z** [comment]
ls -lh `which nvidia-docker`
看一下显示的记录里面，你有没有 x 权限

**Comment by YiqinXu** [comment]
![image](https://user-images.githubusercontent.com/44312441/185089222-bd38b095-cd43-448a-960b-3bc95a8fb129.png)
我的系统没有安装nvidia-docker，应该不是权限问题。
所以使用该项目的requirement是不是得加一个必须安装nvidia-docker呀

**Comment by fenrir-z** [comment]
你用的是什么系统？

**Comment by YiqinXu** [comment]
Ubuntu 16.04

**Comment by fenrir-z** [comment]
应该不可能，至少 which 是内置的。

**Comment by phoenix-xhuang** [comment]
https://github.com/IndustryEssentials/ymir#21-environment-dependencies

里面有运行要求，可以看下

Docker installation:
Installation of Docker and Docker Compose https://docs.docker.com/get-docker/

Installation of NVIDIA Docker https://github.com/NVIDIA/nvidia-docker

**Comment by YiqinXu** [comment]
我看看，谢谢

**Comment by YiqinXu** [comment]
目前只支持使用YOLO v4吗？
如果我想要使用自己的网络来做目标检测，应该怎么配置呢

**Comment by phoenix-xhuang** [comment]
支持的镜像在这里都可以找到，也欢迎上传自己开发的训练镜像
https://github.com/IndustryEssentials/ymir/blob/master/docker_executor/public_index.md

**Comment by YiqinXu** [comment]
我添加了这些镜像，怎么才能让前台算法框架这里显示其他的这些呢。
![image](https://user-images.githubusercontent.com/44312441/185289342-aee853a9-da83-423f-ae0e-38bbcc9a0b8d.png)

**Comment by YiqinXu** [comment]
![image](https://user-images.githubusercontent.com/44312441/185302743-765f73e8-24ee-46f5-8286-76bb4a8264cf.png)
另外我pull了其他镜像，这里也暂时没有显示。
我的机器不能联网，所以是不是公共镜像也不可以用。

**Comment by YiqinXu** [comment]
![image](https://user-images.githubusercontent.com/44312441/185305394-e4caf8c1-11c7-490d-be18-827989aeb350.png)
另外我想进入官方提供的docker images内查看/image-man目录，好像暂时也不可以

**Comment by YiqinXu** [comment]
![20220818-140022](https://user-images.githubusercontent.com/44312441/185305472-9f01f04f-1c29-49f7-abb4-e8ee80311aac.png)
另外，我想要进入官方的这个yolo4的镜像中查看/image-man目录，好像暂时也进不去

**Comment by fenrir-z** [comment]
这个位置的文件，只有通过 ymir 启动训练任务的时候才会由系统生成并挂载进来

**Comment by YiqinXu** [comment]
那怎么在前台界面添加新的镜像还有算法框架呢，离线的环境下。

**Comment by phoenix-xhuang** [comment]
https://docs.docker.com/engine/reference/commandline/load/

**Comment by YiqinXu** [comment]
镜像我load进我的环境了，我的意思是，前台页面了只显示了demo镜像，其他我load进来的都没有，是不是需要什么方法添加一下。
我load过镜像以后，前台界面里镜像还是只有这个。
![image](https://user-images.githubusercontent.com/44312441/185843426-326f20f5-d61f-480a-b5dd-d04361702c06.png)

**Comment by phoenix-xhuang** [comment]
用管理员帐号登录，才有权限添加镜像



系统配置 | 镜像管理 | 我的镜像 | 支持添加自定义镜像到系统中（仅管理员可用）

**Comment by YiqinXu** [comment]
管理员账号是啥呢，我看注册账号的时候不能选择注册管理员账号。

**Comment by phoenix-xhuang** [comment]
.env文件里面有管理员帐号，如果是多人使用注意保密，并在部署前修改

**Comment by YiqinXu** [comment]
好的，谢谢。
是哪个路径下的.dev文件，我目前只看到.env文件

**Comment by phoenix-xhuang** [comment]
对，.env typo

FIRST_ADMIN
FIRST_ADMIN_PASSWORD

**Comment by YiqinXu** [comment]
添加好了，谢谢。
但是我选择添加好的镜像，比如yolo5或者mmdection，算法框架还是只显示yolo4，这个应该怎么修改呢。
![image](https://user-images.githubusercontent.com/44312441/185852325-91a28071-ae90-4f31-82c8-06bc44947c6b.png)

**Comment by phoenix-xhuang** [comment]
算法框架不用管，这个没用，以后会去掉的

**Comment by YiqinXu** [comment]
好的，谢谢~
制作自己的镜像并接入YMIR，前面的文档写的有点没看懂，有没有具体的步骤呀

**Comment by phoenix-xhuang** [comment]
有两篇介绍文档：

https://github.com/IndustryEssentials/ymir/tree/master/docker_executor/sample_executor

https://github.com/IndustryEssentials/ymir/blob/master/docs/ymir-cmd-container.md

**Comment by YiqinXu** [comment]
好的，谢谢~

**Comment by zw1765** [comment]
你好，我训练模型时候也遇到了你这个nvidia-docker执行权限的问题。请问一下你是如何解决这个问题的。
