### ISSUE TITLE
提供ymir开发者手册

### ISSUE THREAD

**Issue by huahuaeshao** [IndustryEssentials/ymir#1109]
希望可以提供技术架构文档，以及ymir的大致设计方案
最好有文档可以指导怎么在ubuntu环境搭建本地可调试的ymir环境
方便代码爱好者更容易理解ymir

**Comment by phoenix-xhuang** [comment]
no plan to support this. feel free to post question here though.

**Comment by phoenix-xhuang** [comment]
will support developer in docker image developing, not in YMIR system developing.
