### ISSUE TITLE
viewer模块手动构建成功以后，出现数据集详情bug

### ISSUE THREAD

**Issue by huahuaeshao** [IndustryEssentials/ymir#1174]
把viewer模块构建成功，但是在数据集详情点击查看页面接口会报500，但是我要是二次进入，或者点击页面上的随机页去刷新就会显示图片
![469ad9cf4ce97dd67e96e62e56411dd](https://user-images.githubusercontent.com/96853551/191439669-1362cc5c-d106-4280-9e66-9ec91051e22e.jpg)
![image](https://user-images.githubusercontent.com/96853551/191439868-7eb3a564-d171-4927-94e1-c0f7906bf70b.png)

**Comment by phoenix-xhuang** [comment]
viewer模块并没有发布
