### ISSUE TITLE
using bash ymir.sh start but isn't successful

### ISSUE THREAD

**Issue by Louis8582** [IndustryEssentials/ymir#1214]
**Describe the issue**
My system is Windows 10 and already installed docker, wsl 2 and check using wsl2 to open docker. But when I go to next step "bash ymir.sh start", it downloaded something like yolo-mining-xxxx, then it closed by itself. I can't pick up the error by it's info.

**To Reproduce**
My installation step:
1. installed docker restart computer
2. installed wsl2 and set docker to use wsl2 then restart
3. use wsl vi to change '$\r' to '\x', if don't do this step it will showed like '$\r' not found .....
4. "bash ymir.sh start" then automatically download something it need
5. closed 

**Expected behavior**
start the ymir. 
**Screenshots**
![image](https://user-images.githubusercontent.com/23739360/193196256-96810c7f-a76f-4149-a3b3-0ff4aad7361a.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: not use

**Additional context**

**Comment by phoenix-xhuang** [comment]
Need to provide labeling tool's ip address

**Comment by Louis8582** [comment]
how to check labeling tool's IP ?   I tryed to set 192.168.1.101, but it said unsupport label tool
![image](https://user-images.githubusercontent.com/23739360/193226014-435b66fb-3248-4044-86e3-df2bfe98cb58.png)
do I need install this tool?

**Comment by phoenix-xhuang** [comment]
what's the value of LABEL_TOOL=? in .env

**Comment by Louis8582** [comment]
nothing
![image](https://user-images.githubusercontent.com/23739360/193226647-43ae53ab-69ed-4866-b1fa-450e68c8fc51.png)

**Comment by phoenix-xhuang** [comment]
delete any space or tab after LABEL_TOOL=
it seems there is some unrecognized content there.
also, ymir is not fully tested on Windows platform. Suggest to use Linux.

**Comment by Louis8582** [comment]
Got it, I will try on ubuntu 18. Thank's
BTW didn't have any char after the LABEL_TOOL= 
so it's not work.

**Comment by phoenix-xhuang** [comment]
https://github.com/IndustryEssentials/ymir/blob/master/ymir.sh#L106
i doubt the above line will work on Windows.

on windows, instead of using ymir.sh, try "docker-compose -f docker-compose.yml down --remove-orphans  && docker-compose -f docker-compose.yml up -d" directly
