### ISSUE TITLE
How do I make a dataset recognizable to ymir?

### ISSUE THREAD

**Issue by liyi93319** [IndustryEssentials/ymir#1333]
**Describe the issue**
I'm trying to begin my first training on ymir with `Sample.zip` that ymir provided.

**To Reproduce**
1. `bash ymir.sh start`
2. create a new project with labels "bowl, cat, cup, spoon"
3. download `sample_dataset.zip` from the "Import Dataset" page and then upload it back
4. examine the newly uploaded dataset

**Expected behavior**
there should be 4 Keywords shown for the newly uploaded dataset

**Screenshots**
ymir counts it as 0

![image](https://user-images.githubusercontent.com/43629316/198446265-9d18812e-a329-433a-a88e-0975b1d1bf57.png)

5. click the "train" action for the dataset

**Expected behavior**
ymir treat the newly uploaded dataset as training set

**Screenshots**
ymir asks me to upload the training set again

![image](https://user-images.githubusercontent.com/43629316/198448383-c3ac6977-0c0c-45f9-96e4-330843ac86a5.png)

![image](https://user-images.githubusercontent.com/43629316/198441189-c87cf63d-a6f3-450e-88ce-c21a1eae7740.png)

**Additional context**
the directory structure is as follows

```
├── annotations
│   ├── bowl.xml
│   ├── cat.xml
│   ├── cup.xml
│   └── spoon.xml
└── images
    ├── bowl.jpg
    ├── cat.jpg
    ├── cup.jpg
    └── spoon.jpg
```

as an example, the content of bowl.xml is shown below

```
<annotation>
	<folder>images</folder>
	<filename>bowl</filename>
	<source>
		<database>MyDatabase</database>
		<annotation>COCO2017</annotation>
		<image>flickr</image>
		<flickrid>NULL</flickrid>
		<annotator>abc@abc.com</annotator>
	</source>
	<owner>
		<flickrid>NULL</flickrid>
		<name>Label Studio</name>
	</owner>
	<size>
		<width>1080</width>
		<height>1350</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>bowl</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>619</xmin>
			<ymin>667</ymin>
			<xmax>1030</xmax>
			<ymax>1055</ymax>
		</bndbox>
	</object>
</annotation>

```

How do I make a dataset recognizable to ymir?

**Comment by fenrir-z** [comment]
can not reproduce this issue on ubuntu 22.04.
what system you are using?

**Comment by liyi93319** [comment]
Ubuntu 18.04, Docker version 20.10.20, build 9fdeb9c

**Comment by fenrir-z** [comment]
i can not reproduce this issue.
can you show me your keyword list (you can access this list in `Keyword` bottom at top of your banner) and your project settings?

**Comment by liyi93319** [comment]
here it is.

![image](https://user-images.githubusercontent.com/43629316/199356011-8d22975d-0e82-4ec9-a2e5-3f841060365f.png)

![image](https://user-images.githubusercontent.com/43629316/199356685-9f7c44e8-7211-4119-bd81-43104f497ac4.png)

![image](https://user-images.githubusercontent.com/43629316/199356719-1ad431d0-8856-47e8-af00-096e28557298.png)

I'm using version 1.1.0.0517, I can replace it with 2.0.0 if needed. Actually I will re-install everything if needed.

**Comment by fenrir-z** [comment]
really strange.

i can not reproduce this issue with both 1.1.0 and 2.0.0.

would you please try:

1. in your Import dataset page, confirm your `Labeling Status` is `Contains Annotations`
2. send me ymir_controller.log in `</path/to/ymir-workplace>/ymir-data/logs/ymir_controller.log`
3. find your repo in `</path/to/ymir-workplace>/sandbox/<your-user-id>/<your-repo-id>`, then `ls -l .mir`, and show me the result
4. if possible, remove whole workplace and try again

**Comment by liyi93319** [comment]
Labeling Status is Contains Annotations.

![image](https://user-images.githubusercontent.com/43629316/199734138-053aab88-a15b-4c94-9c45-fd7f0b2c0232.png)

here is ymir_controller.log
[ymir_controller.log](https://github.com/IndustryEssentials/ymir/files/9929627/ymir_controller.log)

here is the directory structure in </path/to/ymir-workplace>/sandbox/
which one is <my-user-id> and <my-repo-id>?

```
.
├── 0001
│   ├── 000001
│   ├── 000002
│   ├── 000003
│   ├── 000004
│   ├── 000005
│   ├── 000006
│   ├── 000007
│   ├── 000008
│   ├── 000009
│   └── labels.yaml
└── work_dir
    ├── TaskTypeCopyData
    └── TaskTypeImportData
```

**Comment by fenrir-z** [comment]
i can see only one `mir import` command in your ymir_controller.log line 1037, it shows:
``` text
mir import --root /home/dssapce/sf/ymir/ymir-workplace/sandbox/0001/000008 --dataset-name t0000001000008b2b2ef1666881235 --dst-rev t0000001000008b2b2ef1666881235@t0000001000008b2b2ef1666881235 --src-revs master --index-file /home/dssapce/sf/ymir/ymir-workplace/sandbox/work_dir/TaskTypeImportData/t0000001000008b2b2ef1666881235/sub_task/t0000001000008b2b2ef1666881235/index.txt --gen-dir /home/dssapce/sf/ymir/ymir-workplace/ymir-assets -w /home/dssapce/sf/ymir/ymir-workplace/sandbox/work_dir/TaskTypeImportData/t0000001000008b2b2ef1666881235/sub_task/t0000001000008b2b2ef1666881235 --annotation-dir /ymir-sharing/import_dataset_jwozdhda/sample_input_data/annotations --ignore-unknown-types

INFO    : [20221027-14:33:56] utils.py:30:run_command(): run cmd succeed: 
 loaded type id and names: 8
wrting 4 annotations
unknown types: defaultdict(<class 'int'>, {'cat': 1, 'bottle': 1, 'cup': 1, 'bowl': 2, 'spoon': 1})
git result: 
?? annotations.mir
?? context.mir
?? keywords.mir
?? metadatas.mir
?? tasks.mir

[t0000001000008b2b2ef1666881235 c5cd946] importing /home/dssapce/sf/ymir/ymir-workplace/sandbox/work_dir/TaskTypeImportData/t0000001000008b2b2ef1666881235/sub_task/t0000001000008b2b2ef1666881235/index.txt-/ymir-sharing/import_dataset_jwozdhda/sample_input_data/annotations-/home/dssapce/sf/ymir/ymir-workplace/ymir-assets as t0000001000008b2b2ef1666881235
 5 files changed, 15 insertions(+)
 create mode 100644 annotations.mir
 create mode 100644 context.mir
 create mode 100644 keywords.mir
 create mode 100644 metadatas.mir
 create mode 100644 tasks.mir
command done: t0000001000008b2b2ef1666881235@t0000001000008b2b2ef1666881235, return code: 0
|-cmd_run costs 0.26s(0.00m).
```

so your repo root is `/home/dssapce/sf/ymir/ymir-workplace/sandbox/0001/000008`

i also notice that you have choosen "Ignore unknown keywords and annotations" when you import this dataset (and mir import xxx --ignore-unknown-types also shows this), and at this time, there're no cat, bowl, spoon and cup in your `/home/dssapce/sf/ymir/ymir-workplace/sandbox/0001/labels.yaml`, they first appear at line 1475 in your ymir-controller.log

so your timeline is just like:

1. in line 1037, you imported sample_dataset.zip, ignored unknown types, and at this time, cup, spoon, cat, bowl were not appeared in your labels.yaml, so they were ignored
2. before line 1475, you added this four types to your labels.yaml (from Keywords page)
3. after this, i find no import again

can you try import sample-dataset.zip again? if it still goes wrong, please send me ymir_controller.log again, thanks.

**Comment by liyi93319** [comment]
Removing whole workplace solves the problem. Thank you so much!
