### ISSUE TITLE
拉取镜像训练的问题

### ISSUE THREAD

**Issue by GDbbq** [IndustryEssentials/ymir#1336]
1： 想问下怎么修改代码，从现有的容器中直接进行训练？
2： 创建发布自己的镜像，有详细的教程吗？

**Comment by liyi93319** [comment]
try this https://github.com/IndustryEssentials/ymir/tree/master/docker_executor/sample_executor

**Comment by GDbbq** [comment]
![image](https://user-images.githubusercontent.com/86715812/198910826-bcd37c94-d884-4201-b800-ab223cb2a196.png)
这个步骤实现的代码是哪里呢，我想更改现有的镜像拉取创建容器的方式，每次训练，只需启动现有的容器进行训练。

**Comment by fenrir-z** [comment]
You can find code here
https://github.com/IndustryEssentials/ymir/tree/master/docker_executor/sample_executor/app
