### ISSUE TITLE
Is there a way, e.g. a piece of configuration in `.env`, to start ymir with `LABEL_TOOL=None` such that I don't have to type 3 repeatedly?

### ISSUE THREAD

**Issue by liyi93319** [IndustryEssentials/ymir#1348]
**Describe the issue**
Is there a way, e.g. a piece of configuration in `.env`, to start ymir with `LABEL_TOOL=None` such that I don't have to type 3 repeatedly?

![image](https://user-images.githubusercontent.com/43629316/199752285-24d5234e-f105-46c8-890f-95f51e4541b6.png)

**Comment by fenrir-z** [comment]
if you REALLY need no label tools, just comment start_label_tool in ymir.sh
