### ISSUE TITLE
标签含有英文分号';'时可能会导致建立标注任务失败

### ISSUE THREAD

**Issue by huu3301** [IndustryEssentials/ymir#1350]
Describe the bug
1.1.0和2.0.0版本都存在这个问题，就是当添加的标签含有英文分号时可能会导致建立标注任务失败（训练任务可能也有该问题）

To Reproduce

1、添加包含;符号的标签（如cdefg;fffaaa）。
2、创建标注任务的时候使用该标签。

会出现CmdExport失败（cmd export时class_names是以;来拆分的），从而创建标注任务失败。
command_run_in_out.py:164: trace: cmd exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/command_run_in_out.py", line 106, in wrapper
    ret = f(mir_root=mir_root, src_revs=src_revs, dst_rev=dst_rev, work_dir=work_dir, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mir/commands/export.py", line 68, in run_with_args
    raise MirRuntimeError(error_code=MirCode.RC_CMD_INVALID_ARGS,
mir.tools.errors.MirRuntimeError: code: 160001, message: unknown class names: ['cdefg', 'fffaaa']

**Comment by fenrir-z** [comment]
标注不能含有英文分号
