### ISSUE TITLE
ERROR: Version mismatch: file ./docker-compose.yml specifies version 3.3 but extension file ./docker-compose.labelfree.yml uses version 3.1

### ISSUE THREAD

**Issue by planetb113** [IndustryEssentials/ymir#1431]
**Describe the bug**

ERROR: Version mismatch: file ./docker-compose.yml specifies version 3.3 but extension file ./docker-compose.labelfree.yml uses version 3.1

**To Reproduce**
1. `bash ymir.sh start`

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Server OS: [e.g. Ubuntu] ubuntu:18.04
 - Ymir Version [e.g. 0.5.0] 
 - Local Browser [e.g. chrome]

**Additional context**

**Comment by IJtLJZ8Rm4Yr** [comment]
You can upgrade docker-compose to 1.29.2 or higher and try again
