### ISSUE TITLE
How to change lab studio to lab free

### ISSUE THREAD

**Issue by luoluo2001108** [IndustryEssentials/ymir#1517]
Hello：

when install ymir GUI ,at first ,I choose Label studio,,Now I want to change to Label free,
how can I do for this ？

Thank you

**Comment by Aryalfrat** [comment]
If you are trying version 2.0.2 or later
1. update the value of LABEL_TOOL in .env to label_free
2. docker-compose down && docker-compose up -d
3. stop label studio and start label free

If you are using a version prior to 2.0.2

1. update the value of LABEL_TOOL in .env to label_free
2. update LABEL_TOOL_TOKEN in .env to "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9. eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY0ODg3MDQwMiwianRpIjoiZGE2YjI3NmEtNjRmZi00MmI5LTgxZWEtNWQ3NTg5YjEwYTBkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InltaXJAaW50ZWxsaWYuY29tIiwibmJmIjoxNjQ4ODcwNDAyLCJleHAiOjQ4MDI0NzA0MDJ9 .knxsip1oXKd8y_J3-epg74ebPsuKiYaOfdtNz6gvLkA"
3. docker-compose down && docker-compose up -d
4. stop label studio and start label free
