### ISSUE TITLE
Does this project support import and train PyTorch & TF models?

### ISSUE THREAD

**Issue by charlestamz** [IndustryEssentials/ymir#1678]
Hi there.

**Comment by phoenix-xhuang** [comment]
yes，machine learning env (pytorch or tf) is designed to be run in a separated docker container, and communicate with YMIR in a designed data interface.

check the following docs. you will need a docker container that contains pytorch or tf, and import it into YMIR system

https://github.com/IndustryEssentials/ymir/tree/master/docker_executor/sample_executor

https://github.com/IndustryEssentials/ymir/blob/master/dev_docs/ymir-cmd-container.md
