### ISSUE TITLE
无空闲GPU

### ISSUE THREAD

**Issue by JankinHou** [IndustryEssentials/ymir#1769]
我在使用ymir进行训练并完成训练后，进行验证，一直提示无空闲GPU
查看GPU使用
![image](https://github.com/IndustryEssentials/ymir/assets/38063730/4375b5d2-3e4f-4187-b0a2-a77ca3050949)

应该是有进程在占用GPU的资源，导致GPU占用率超过了30%，因此无法使用。
但除了ymir，当前机器上没有启用其他进程占用GPU。
根据以下进城查看详情
 2788214      C   /usr/local/bin/python            4477MiB

ps -p 2788214 -o pid,user,%cpu,%mem,vsz,rss,tty,stat,start,time,command
![image](https://github.com/IndustryEssentials/ymir/assets/38063730/85b81c09-08aa-437f-b687-58875b050398)

这个进程是否是ymir相关的一个服务，这个服务会自动关闭吗？或者说是哪一步出错了导致没有自动停止。等待时间较长后仍然无法自动关闭，GPU一直无法用来验证

**Comment by phoenix-xhuang** [comment]
ymir正常运行不会占用GPU

**Comment by JankinHou** [comment]
> ymir正常运行不会占用GPU

我发的这个进程和ymir没关系吗？我确认再三，服务器上确实只跑了一个ymir。真奇怪啊
![3CD4D7A4](https://github.com/IndustryEssentials/ymir/assets/38063730/086e353d-4136-46d9-acd6-8f785294eb58)

**Comment by phoenix-xhuang** [comment]
kill掉试试
