### ISSUE TITLE
基础镜像的Dockerfile文件哪里可以找到？

### ISSUE THREAD

**Issue by gavinju** [IndustryEssentials/ymir#1771]
请教下，像pubalglib/model_deploy_nginx:1.0.0、及industryessentials/ymir-backend:release-2.5.0，这些镜像对应的Dockerfile文件哪里可以找到？
谢谢

**Comment by phoenix-xhuang** [comment]
ymir-backend的Dockerfile在源代码src里

pubalglib未开源
