### ISSUE TITLE
关于推理结果只能返回整型的问题

### ISSUE THREAD

**Issue by CatchBeliF-TAT** [IndustryEssentials/ymir#1772]
您好，不好意思打扰了！
想问一下推理结果只能返回整型是为了在平台上可视化画图吗？
这边本地和YMIR平台在相同推理结果的情况下，评估得到的mAP不一致，发现是YMIR平台转换推理结果的时候取了整型，不取整型会报错？由于整型的评估结果 和 不取整型的评估结果存在差距，请问这个接口可以修改吗？在哪里可以修改？谢谢！🙏
![image](https://github.com/IndustryEssentials/ymir/assets/88470384/ddfeaf62-8297-42a2-844e-d7c75bc8c06a)
![image](https://github.com/IndustryEssentials/ymir/assets/88470384/c6b01d21-9238-49fe-b290-3dcf8625c7a2)

**Comment by fenrir-z** [comment]
> 这边本地和YMIR平台在相同推理结果的情况下，评估得到的mAP不一致，发现是YMIR平台转换推理结果的时候取了整型

这个结论有点奇怪。如果是目标检测类型的项目，ymir 采用 pycocotools 计算其 mAP，按道理说，结果框取整型和取浮点对于结果的影响并不大，我想进一步了解一下你那边的实验结果，即：取整型和取浮点，其结果差距到底有多少。

如果想将框的整型改为浮点，需要做出以下改动：
1. 推理镜像的改动
  a. 改动 rw.Annotation 的结构，里面有个 Box，将其 x, y, w, h 类型全改成 float
  b. 同时，改动日志上出错的这行，将其前面的 int 换成 float
3. YMIR COMMAND 的改动
  a. ymir/command/proto/mir_command.proto 文件中的 Rect 结构，将 x, y, w, h 全部改成 float
  b. 在 command 目录下执行./update_proto_py.sh
  c. ymir/command/mir/tools/annotations.py 文件中的 L110-L113，以及 L149-L152，int 改成 float
  d. 重新打包 ymir backend 镜像并运行
