### ISSUE TITLE
状态不可用是什么原因导致的？

### ISSUE THREAD

**Issue by xiaocaoxu** [IndustryEssentials/ymir#1779]
![image](https://github.com/IndustryEssentials/ymir/assets/42837678/310365d2-6223-47e8-ae34-02749ef84426)

**Comment by phoenix-xhuang** [comment]
多数是任务失败，查看下工作目录下的controller log，应该有报错

**Comment by xiaocaoxu** [comment]
![image](https://github.com/IndustryEssentials/ymir/assets/42837678/d0b0ec55-38d4-488a-a1cd-1f81d7ee27b3)
服务器是centos系统，PermissionError: [Errno 13] Permission denied: 'nvidia-docker'，不过是有装nvidia-docker，
![image](https://github.com/IndustryEssentials/ymir/assets/42837678/45eb9a75-1427-4af5-8173-6321318eceb0)
是权限问题吗？

**Comment by xiaocaoxu** [comment]
问题解决了，nvidia-docker;65518467名字改成nvidia-docker就可以了。

**Comment by zw1765** [comment]
我也遇到这个问题了。请问一下nvidia-docker;65518467名字在哪里修改呀

**Comment by xiaocaoxu** [comment]
在/bin目录下

**Comment by zw1765** [comment]
![2023-12-01 12-09-27屏幕截图](https://github.com/IndustryEssentials/ymir/assets/86357595/851ce44d-1cc0-4ffc-8cf4-d811666d4fc1)
我的目录下是这样的

**Comment by zw1765** [comment]
我的/bin目录下的nvidia-docker是空的
![2023-12-01 14-03-30屏幕截图](https://github.com/IndustryEssentials/ymir/assets/86357595/4ec02a7a-9aab-4c98-a260-44170af640d7)

**Comment by zw1765** [comment]
运行报错也是说权限问题
![2023-12-01 14-05-12屏幕截图](https://github.com/IndustryEssentials/ymir/assets/86357595/17c517bd-1517-4fda-8c2f-7c22fd2ab681)

**Comment by xiaocaoxu** [comment]
nvidia-docker version看一下
![image](https://github.com/IndustryEssentials/ymir/assets/42837678/5087abf8-b7a1-49d1-9c88-70d9e0e18250)
which nvidia-docker
![image](https://github.com/IndustryEssentials/ymir/assets/42837678/4b8175b6-44a9-4247-8bee-4909acdcc1ab)

**Comment by zw1765** [comment]
找不到命令
![2023-12-01 14-22-24屏幕截图](https://github.com/IndustryEssentials/ymir/assets/86357595/2e01e6fd-53d6-4541-8495-ea254fdfba44)

**Comment by zw1765** [comment]
docker version 
![2023-12-01 14-33-49屏幕截图](https://github.com/IndustryEssentials/ymir/assets/86357595/5dfca21a-c116-43aa-a9b0-7e1d84e05622)

**Comment by xiaocaoxu** [comment]
nvidia-docker重装一下吧，可能安装方式有问题包括tool
