### ISSUE TITLE
如何增加调用国产显卡

### ISSUE THREAD

**Issue by NEHCMA** [IndustryEssentials/ymir#1780]
![image](https://github.com/IndustryEssentials/ymir/assets/65799303/39e5c8e7-2f90-4c33-9f7e-b7f1332a0675)
![image](https://github.com/IndustryEssentials/ymir/assets/65799303/67b6b821-9218-48f8-93eb-2f508883b0ef)
想将该平台对国产gpu进行适配 
将标注处进行修改，就可以拉起driver嘛

**Comment by goldSunshine** [comment]
大概率不行的，因为训练容器也需要适配国产gpu，具体了来说就是pytorch，yolo要适配国产GPU。比如昇腾就不适配pytorch，有自己的一套命令
