### ISSUE TITLE
模型训练运行权限报错

### ISSUE THREAD

**Issue by zw1765** [IndustryEssentials/ymir#1782]
项目大佬好。我最近使用这套平台部署，但是遇到了下面这个问题。
运行训练时候报错如下：
![2023-12-01 14-09-50屏幕截图](https://github.com/IndustryEssentials/ymir/assets/86357595/48dd601f-b6e3-4780-8a83-8519ca61c697)
打开详细信息：
![2023-12-01 14-05-12屏幕截图](https://github.com/IndustryEssentials/ymir/assets/86357595/014b6e86-eef0-4184-b14a-39ad6b948373)
网上搜不到解决方法。求助大佬。

**Comment by ahpu2014** [comment]
哥们，解决了吗，我也遇到了同样的问题；

**Comment by zw1765** [comment]
没有，找不到问题原因

**Comment by ahpu2014** [comment]
你在你的终端直接运行 nvidia-docker有报错吗，应该是这里的问题；

**Comment by zw1765** [comment]
报错nvidia-docker：未找到命令

**Comment by ahpu2014** [comment]
docker 降级就可以了，希望可以帮到你

**Comment by zw1765** [comment]
> docker 降级就可以了，希望可以帮到你

谢谢你，降级后问题解决了。

**Comment by mjq2020** [comment]
> > docker 降级就可以了，希望可以帮到你
> 
> 谢谢你，降级后问题解决了。

我也遇到了相同的问题，请问docker需要降到哪个版本可以呀，我目前是24.0.7,

**Comment by goldSunshine** [comment]
这是因为ymri的训练任务都是通过docker跑的，启动docker使用的是nvidia-docker命令，所以需要安装nvidia-docker。

**Comment by zw1765** [comment]
降低版本后，开始还行。现在用不了了，不知道是哪里 的问题

**Comment by phoenix-xhuang** [comment]
安装下nivida-docker

**Comment by zhangJoel** [comment]
> 降低版本后，开始还行。现在用不了了，不知道是哪里 的问题

您好，请问哪个docker版本可行？
