### ISSUE TITLE
ymir-workplace/ymir-models 下的模型格式是什么？

### ISSUE THREAD

**Issue by karmueo** [IndustryEssentials/ymir#1783]
训练完的模型在ymir-workplace/ymir-models是一个3c76c182282c4db57a4ff0217b06279d99945534文件。

**Comment by danny-zhu** [comment]
这里公司官网上的介绍 https://www.viesc.com/document/README_zh-CN.html#901

成功完成训练后，系统会输出模型的 id，用户可以根据这个 id 到 --model-location 位置找到对应的文件，它事实上是一个 tar 文件，可以直接使用 tar 命令解压，得到 params 和 json 格式的 mxnet 模型文件。

**Comment by zhangJoel** [comment]
我用yolo训练后，下载模型文件后按照tar文件解压，得到 一个onnx模型和一个pt文件，请参考
