### ISSUE TITLE
自制镜像

### ISSUE THREAD

**Issue by ahpu2014** [IndustryEssentials/ymir#1786]
有朋友们在自制镜像吗？如果有可以沟通一下。

**Comment by zw1765** [comment]
> 有朋友们在自制镜像吗？如果有可以沟通一下。

好像公开的镜像限制用不了

**Comment by danny-zhu** [comment]
公开的镜像可以用，下载速度慢，可以自己翻墙用docker pull拉取镜像，再通过平台拉取，平台会检测到本地镜像仓库已经有镜像文件，会更新可用镜像列表。

**Comment by ahpu2014** [comment]
我想扔进去自己的算法




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IndustryEssentials/ymir"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IndustryEssentials/ymir] 自制镜像 (Issue #1786)





 
公开的镜像可以用，下载速度慢，可以自己翻墙用docker pull拉取镜像，再通过平台拉取，平台会检测到本地镜像仓库已经有镜像文件，会更新可用镜像列表。

**Comment by phoenix-xhuang** [comment]
制作指南参考 https://github.com/IndustryEssentials/ymir/tree/master/docker_executor/sample_executor
