### ISSUE TITLE
Can not log in local YMIR server

### ISSUE THREAD

**Issue by MasonSuWei** [IndustryEssentials/ymir#287]
Hello. First thanks for wonderful YMIR Project. I just install YMIR GUI on my computer, the app is running. But I can not log in the app after I enter the user name and password. Is there a way to debug the problem? For example log file or app output.

**Comment by Aryalfrat** [comment]
Try this account please: https://github.com/IndustryEssentials/ymir/blob/master/.env#L10
And password: https://github.com/IndustryEssentials/ymir/blob/master/.env#L11
This is the default administrator account when first deployed, you can configure it in the environment variables. All other accounts you register need to be approved by the administrator account before you can log in.

**Comment by MasonSuWei** [comment]
Hello, do I need to change the following variables in .env?
**APP_SECRET_KEY
APP_API_KEY**

After I use the following username and password, the app still do not let me in

FIRST_ADMIN=admin@example.com
FIRST_ADMIN_PASSWORD=12345678

**The following is request header**
POST /api/v1/auth/token HTTP/1.1
Host: 127.0.0.1:12001
Connection: keep-alive
Content-Length: 291
sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"
Accept: application/json, text/plain, */*
Authorization: Bearer null
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7Op0lUbQrVVBtfJQ
Origin: http://127.0.0.1:12001
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://127.0.0.1:12001/login?redirect=/home/portal
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _xsrf=2|bc1bdfe1|4d96cf96c5ad425cb90d98a6546e7520|1621127996; vdl_lng=en; Hm_lvt_63a600296f8a71f576c4806376a9245b=1621139310; Hm_lpvt_63a600296f8a71f576c4806376a9245b=1621377828

**The following is the respond.**
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.21.6</center>
</body>
</html>

**Comment by Aryalfrat** [comment]
What is your startup method? Is it with docker compose or manually?
Can you give me your .env setup parameters please?

**Comment by MasonSuWei** [comment]
I use the following cmd to start ymir.

sudo sh ymir.sh start

the following is the cmd's output.
Welcome to Ymir world.
ymir.sh: 84: ymir.sh: [[: not found
Would you allow YMIR to send us automatic reports helps us prioritize what to fix and improve in YMIR?
These reports can include things like task type, how much resources you’re using. NO personal information collected.
You choose (Y/n)?n
Using default tag: latest
latest: Pulling from industryessentials/executor-det-yolov4-training
Digest: sha256:e3c7a94c220b3e8fe062788c94bbfd123316b26abddd002f8d3a9e479acbcf81
Status: Image is up to date for industryessentials/executor-det-yolov4-training:latest
docker.io/industryessentials/executor-det-yolov4-training:latest
Using default tag: latest
latest: Pulling from industryessentials/executor-det-yolov4-mining
Digest: sha256:34291426b25ae5374a93fddf28a06c52b2c90b6f90bbc597703ce5f4afdce302
Status: Image is up to date for industryessentials/executor-det-yolov4-mining:latest
docker.io/industryessentials/executor-det-yolov4-mining:latest
[+] Running 1/0
 ⠿ ymir  Warning: No resource found to remove                                                                                                                                                                                            0.0s
ymir.sh: 59: ymir.sh: [[: not found

in prod mode, pulling images.
[+] Running 7/7
 ⠿ redis Pulled                                                                                                                                                                                                                          2.9s
 ⠿ tensorboard Pulled                                                                                                                                                                                                                    2.9s
 ⠿ clickhouse Pulled                                                                                                                                                                                                                     2.9s
 ⠿ web Pulled                                                                                                                                                                                                                            2.9s
 ⠿ backend Pulled                                                                                                                                                                                                                        5.1s
 ⠿ viz-redis Pulled                                                                                                                                                                                                                      2.9s
 ⠿ db Pulled                                                                                                                                                                                                                             4.7s
[+] Running 8/8
 ⠿ Network ymir_ymirnetwork      Created                                                                                                                                                                                                 0.2s
 ⠿ Container ymir-viz-redis-1    Started                                                                                                                                                                                                 5.8s
 ⠿ Container ymir-tensorboard-1  Started                                                                                                                                                                                                 8.6s
 ⠿ Container ymir-clickhouse-1   Started                                                                                                                                                                                                 7.7s
 ⠿ Container ymir-db-1           Started                                                                                                                                                                                                 6.8s
 ⠿ Container ymir-redis-1        Started                                                                                                                                                                                                 6.4s
 ⠿ Container ymir-backend-1      Started                                                                                                                                                                                                 9.1s
 ⠿ Container ymir-web-1          Started                                                                                                                                                                                                10.7s

The following is my .env file.
[env.zip](https://github.com/IndustryEssentials/ymir/files/8022692/env.zip)

**Comment by Aryalfrat** [comment]
Or you can join our SLACK, we will answer your questions in real time: https://join.slack.com/t/ymir-users/shared_invite/zt-ywephyib-ccghwp8vrd58d3u6zwtG3Q

**Comment by phoenix-xhuang** [comment]
try to replace the LABEL_TOOL_URL LABEL_TOOL_PORT in your .env with real ip+port

**Comment by skytodmoon** [comment]
Hello, guys, I met the same problem, any suggestions?
`# PATH
YMIR_PATH=${PWD}/ymir-workplace
BACKEND_SANDBOX_ROOT=${YMIR_PATH}/sandbox

# PORT
NGINX_PORT=12001

# API
APP_SECRET_KEY=replace_with_your_secret_key
PUBLIC_DATASET_OWNER=1
FIRST_ADMIN=admin@test.com
FIRST_ADMIN_PASSWORD=12345678
APP_API_KEY=replace_with_your_app_api_key
VIZ_TIMEOUT=30
REGISTRATION_NEEDS_APPROVAL=False

# Shared Image
WUFOO_URL=https://alfrat.wufoo.com/api/v3/forms/sk6d8gy1eudnz5/entries.json
WUFOO_AUTHORIZATION=Basic Q1ZKSi1ISzlJLVpOR0ItUzk1RTphbnlfdmFsdWVfd2lsbF9kbw==
SHARED_DOCKER_IMAGES_URL=https://raw.githubusercontent.com/IndustryEssentials/ymir/master/docker_executor/public_index.md

# Database (MySQL)
MYSQL_ROOT_PASSWORD=123456
MYSQL_DATABASE=ymir
MYSQL_INITIAL_USER=admin
MYSQL_INITIAL_PASSWORD=adminadmin

# label tool env
LABEL_TOOL=label_studio
# Note format: LABEL_TOOL_HOST_IP=http(s)://(ip)
LABEL_TOOL_HOST_IP=http://10.180.77.171
LABEL_TOOL_HOST_PORT=8763
LABEL_TOOL_HOST_URL=${LABEL_TOOL_HOST_IP}:${LABEL_TOOL_HOST_PORT}
LABEL_TOOL_TOKEN="Token 4b1fe90934bd90ce6af4e9c5336a43cc334c68e1"
LABEL_TASK_LOOP_SECONDS=10
LABEL_TOOL_S3_PORT=9099

# tensorboard env
TENSORBOARD_ROOT=${YMIR_PATH}/ymir-tensorboard-logs

# Debugging
USE_200_EVERYWHERE=True
MAX_WORKERS=8

# Email Notification
# EMAILS_ENABLED=False
# FRONTEND_ENTRYPOINT=
# SMTP_TLS=
# SMTP_PORT=
# SMTP_HOST=
# SMTP_USER=
# SMTP_PASSWORD=
# EMAILS_FROM_EMAIL=
# EMAILS_FROM_NAME=ymir-project
# EMAIL_RESET_TOKEN_EXPIRE_HOURS=1
# EMAIL_TEMPLATES_DIR=/app/email-templates/build

# Anonymous feedback
ALLOW_ANONYMOUS_FEEDBACK=True
ANONYMOUS_UUID=cfaeb8e3-7f61-4ec6-bc84-4f7deefa3ea7

# nvidia for gpu, runc for cpu.
SERVER_RUNTIME=nvidia`
