### ISSUE TITLE
Running YMIR in WSL2 fails

### ISSUE THREAD

**Issue by tolsicsse** [IndustryEssentials/ymir#324]
Hi
I fail to start YMIR on my windows PC using WSL2. I thinnk it is due to the docker compose is v2 but your code uses v1 (or something similar). See the execution trace below. I have checked that the Nvidia GPU drivers etc. are correctly installed. 
/Tomas

Using default tag: latest
latest: Pulling from industryessentials/executor-det-yolov4-training
Digest: sha256:ab7fd377e7945ad668547921ee8b0ddd2a24a55c655614cc836ff5e5d93e1855
Status: Image is up to date for industryessentials/executor-det-yolov4-training:latest
docker.io/industryessentials/executor-det-yolov4-training:latest
Using default tag: latest
latest: Pulling from industryessentials/executor-det-yolov4-mining
Digest: sha256:17f6e5bf7192780acf897a8e24b6c10b280287daa4953e67e27d17bb483f6477
Status: Image is up to date for industryessentials/executor-det-yolov4-mining:latest
docker.io/industryessentials/executor-det-yolov4-mining:latest
[+] Running 6/6
 ⠿ Container ymir-clickhouse-1   Removed                                                                           0.1s
 ⠿ Container ymir-db-1           Removed                                                                           0.1s
 ⠿ Container ymir-viz-redis-1    Removed                                                                           0.1s
 ⠿ Container ymir-tensorboard-1  Removed                                                                           0.1s
 ⠿ Container ymir-redis-1        Removed                                                                           0.1s
 ⠿ Network ymir_ymirnetwork      Removed                                                                           0.2s

in prod mode, pulling images.
[+] Running 7/7
 ⠿ backend Pulled                                                                                                  1.6s
 ⠿ viz-redis Pulled                                                                                                1.6s
 ⠿ web Pulled                                                                                                      1.6s
 ⠿ clickhouse Pulled                                                                                               1.6s
 ⠿ tensorboard Pulled                                                                                              1.6s
 ⠿ redis Pulled                                                                                                    1.6s
 ⠿ db Pulled                                                                                                       1.6s
[+] Running 6/6
 ⠿ Network ymir_ymirnetwork      Created                                                                           0.0s
 ⠿ Container ymir-tensorboard-1  Created                                                                           0.1s
 ⠿ Container ymir-redis-1        Created                                                                           0.1s
 ⠿ Container ymir-viz-redis-1    Created                                                                           0.1s
 ⠿ Container ymir-clickhouse-1   Created                                                                           0.1s
 ⠿ Container ymir-db-1           Created                                                                           0.1s
 ⠋ Container ymir-backend-1      Creating                                                                          0.0s
Error response from daemon: Unknown runtime specified nvidia

**Comment by tolsicsse** [comment]
I found this comment that might be a hint: https://github.com/docker/compose/issues/6691#issuecomment-514429646

**Comment by under-chaos** [comment]
@tolsicsse  Could you please:
1, check docker compose version. Ymir needs [Docker Compose v1.27.0+](https://docs.docker.com/compose/gpu-support/)
2, check nvdia-docker. like `nvidia-docker image ls`

**Comment by tolsicsse** [comment]
> docker compose version
Docker Compose version v2.2.3

Yes I have the wrong version but  when I followed the instruction you linked to it was not possible to install any other version of docker composer. It is a little bit complicated with the integration between WSL2 and the windows docker desktop. How do I change the composer version?

**Comment by under-chaos** [comment]
> > docker compose version
> > Docker Compose version v2.2.3
> 
> Yes I have the wrong version but when I followed the instruction you linked to it was not possible to install any other version of docker composer. It is a little bit complicated with the integration between WSL2 and the windows docker desktop. How do I change the composer version?

Because Ymir is currently only running in a Linux environment, so I check the doc, seems [Install Docker Desktop on Windows](https://docs.docker.com/desktop/windows/install/)  defatul is v2
The reason of the problem is [docker compose runtime](https://github.com/IndustryEssentials/ymir/blob/master/docker-compose.yml#L7), maybe you can:
1，check  [wsl gpu support doc](https://docs.docker.com/desktop/windows/wsl/#gpu-support), find way to change the runtime
2, find a way to switch docker compose to v1
2, switch to pure linux run ymir
