### ISSUE TITLE
目前不支持windows部署吗？

### ISSUE THREAD

**Issue by ASentry** [IndustryEssentials/ymir#626]

**Comment by phoenix-xhuang** [comment]
是的，系统并没有在windows下面做过完整功能测试，可能会有未知问题影响使用

**Comment by ASentry** [comment]
![image](https://user-images.githubusercontent.com/22337778/167809758-1ed903e9-5e2e-41a4-ac7c-4f609687cd33.png)
这东西是在干嘛
