### ISSUE TITLE
It can't pull industryessentials/executor-det-yolov4-training from aliyun mirror

### ISSUE THREAD

**Issue by zhangchunsheng** [IndustryEssentials/ymir#631]
```shell
docker pull industryessentials/executor-det-yolov4-training
```

You can see that the layer 11323ed2c653 is Downloading, but can't find any thing to download.

```
8412b44cad21: Pulling fs layer

Using default tag: latest
latest: Pulling from industryessentials/executor-det-yolov4-training
11323ed2c653: Downloading
aac8cf1d1c79: Download complete
fc85802d11de: Download complete
5ecaf0dceab7: Download complete
52ea4560e85a: Download complete
de9ca64a95e6: Download complete
e4165bf6e171: Download complete
77cc6fb46c25: Downloading [================================>                  ]  519.5MB/804.9MB
f54c7e16b308: Download complete
4e21240e72c2: Downloading [=================================>                 ]  359.9MB/532.4MB
```

It will pull again from docker hub. It will be very slow in China. Please provider another docker registry in China.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/831839/168006737-ba4b9798-0335-4698-889d-2cd671b387be.png">

**Comment by Zhang-SJ930104** [comment]
You can use aliyun to pull images several times, because it may be affected by the transmission speed。
You can also refer to the link below to improve the speed。
https://yeasy.gitbook.io/docker_practice/install/mirror
