### ISSUE TITLE
why my nvidia driver is broken 

### ISSUE THREAD

**Issue by ChinaRush** [IndustryEssentials/ymir#639]
**Describe the issue**
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #1: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown

**To Reproduce**
1. Go to 'bash ymir.sh start'
2. See error

**Expected behavior**
我运行 bash ymir.sh start ,进入了web页面，成功上传自己的数据包zip文件，点击label在进入标注页面，标注页面无法显。重启之后，发现显卡驱动有问题，我的显示器异常，用nvidia-smi 命令，显示无显卡驱动，为什么会破坏我的显卡驱动。而重新运行dash ymir.sh start, 能进入web页面，但一段时间之后，终端报错。web页面还是在
**Screenshots**，
![Screenshot from 2022-05-13 09-37-44](https://user-images.githubusercontent.com/39917677/168194424-e644bd5d-d88a-44c5-8317-e5695f1179f1.png)
![Screenshot from 2022-05-13 09-42-17](https://user-images.githubusercontent.com/39917677/168194518-c17890d3-9ca9-4a4a-829a-c1f33adf5599.png)
![Screenshot from 2022-05-13 09-45-27](https://user-images.githubusercontent.com/39917677/168194904-bbe0a256-8990-4d64-b7ab-e79c46e7b19a.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu20.04 LTS]
 - Browser [chrome 版本 101.0.4951.64]
 - docker-version:20.10

**Comment by ChinaRush** [comment]
this error was fixed after reinstalling nvidia-driver

**Comment by Zhang-SJ930104** [comment]
OK.
If you still encounter this problem, you can ask us again.
If you encounter the same problem next time,you can give screenshots for .env file and docker-compose.yml file to help me troubleshoot problems.I want to confirm whether the configuration is correct according to the screenshot.
Thank you for try our service.
