### ISSUE TITLE
label-free can't work

### ISSUE THREAD

**Issue by ChinaRush** [IndustryEssentials/ymir#647]
**Describe the issue**
label-free can't work when i click the label 

**To Reproduce**
1. Go to 'Label' 
2. Upload my dataset  (data.zip just contains 18 pictures)
3. See error

**Screenshots**

I want to label new image dataset, when I get the zip file uploaded, Ijust 18 pictures, it has loaded nearly one day with nothing . But I have import a dataset with 1k pictures in 10 seconds

![Screenshot from 2022-05-14 15-18-07](https://user-images.githubusercontent.com/39917677/168415466-f6e934fe-b4c6-4989-8eb2-74f5d51ff3a7.png)

when I enter the label-free site ,this also show data reading.

![Screenshot from 2022-05-14 14-51-03](https://user-images.githubusercontent.com/39917677/168414678-7068e4df-d5a0-4ca6-a433-d7ea537c2829.png)

when i clicked the label or import button ,it reports "The current project is reading data.Please refresh the project list and try again
![Screenshot from 2022-05-14 14-57-48](https://user-images.githubusercontent.com/39917677/168414732-166d3de2-24ca-4d80-b606-7b3ca5d9ebe3.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04 LTS]
 - Browser [chrome]
 - docker-version 20.10
 - 

**Additional context**
I also get label-free repo via `git clone  https://github.com/IndustryEssentials/label-free.git`, it's the same problem, is there something wrong with the label-free platform?  or am i doing something wrong?

**Comment by ChinaRush** [comment]
I have tried another tool Label Studio, and it works well.

**Comment by phoenix-xhuang** [comment]
@yance-dev

**Comment by yance-dev** [comment]
> 

@ChinaRush We have fix this. plz  do this in your ymir dir:

```bash
git pull origin master

bash ymir.sh
```

**Comment by ChinaRush** [comment]
Thanks a lot.I had tried it and  i got  the same error.
