### ISSUE TITLE
ARM Rebuild

### ISSUE THREAD

**Issue by shenwenshi** [IndustryEssentials/ymir#657]
1、cd ymir/backend/src/ymir_app/deploy/redis
2、docker build -t industryessentials/ymir-backend-redis -f Dockerfile .

after rebuilding ,run the bash ymir.sh start
loging:
standard_init_linux.go:219: exec user process caused: exec format error

**Comment by phoenix-xhuang** [comment]
check https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error

**Comment by shenwenshi** [comment]
uname -a
Linux nvidia-desktop 4.9.201-tegra #1 SMP PREEMPT Fri Jul 9 08:56:59 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by phoenix-xhuang** [comment]
check the previous stackoverflow link:

# Build for ARM64 (default)
docker build -t <image-name>:<version>-arm64 .

# Build for ARM64 
docker build --platform=linux/arm64 -t <image-name>:<version>-arm64 .

# Build for AMD64
docker build --platform=linux/amd64 -t <image-name>:<version>-amd64 .
