### ISSUE TITLE
Support cluster mode to deploy ?

### ISSUE THREAD

**Issue by stubbornrock** [IndustryEssentials/ymir#669]
**Support cluster mode to deploy ?**
I've deployed and test, It's very cool，But I have multiple GPU nodes. Do we support cluster mode to deploy? 
If not,  We plan to support it?

**Comment by phoenix-xhuang** [comment]
we are planning to add support for distributing training task to remote GPU machine in next Major version.

**Comment by stubbornrock** [comment]
> we are planning to add support for distributing training task to remote GPU machine in next Major version.
ok，thanks, When do we plan to release the next major version？

**Comment by phoenix-xhuang** [comment]
June, probably.

**Comment by stubbornrock** [comment]
ok，thanks
