### ISSUE TITLE
RC_CMD_ERROR_UNKNOWN: unkown error

### ISSUE THREAD

**Issue by Sn34931** [IndustryEssentials/ymir#692]
my ymir service is running in a virtual machine， when I train the model, it prompts an error
<html><body>
<div class="ant-card-head"><div class="ant-card-head-wrapper"><div class="ant-card-head-title"><div class="ant-row" style="row-gap: 0px;"><div style="flex: 1 1 auto;" class="ant-col">model_group_23 &gt; Train</div><div class="ant-col"></div></div></div></div></div><div class="content___3L-NX"><div class="ant-descriptions ant-descriptions-bordered infoTable"><div class="ant-descriptions-header"><div class="ant-descriptions-title">Model Detail</div></div><div class="ant-descriptions-view">

Model Name | model_group_23 V2 | mAP | 0.00%
-- | -- | -- | --

</div></div></div>
</body>
</html>

<html><body>
<div class="taskDetail"><div class="ant-descriptions ant-descriptions-bordered infoTable"><div class="ant-descriptions-header"><div class="ant-descriptions-title"><div class="title">Task State</div></div></div><div class="ant-descriptions-view">

Current State | Invalid
-- | --

</div></div></div>
</body>
</html>

<html><body>
<div class="ant-descriptions-header"><div class="ant-descriptions-title"><div class="title">Failure</div></div></div><div class="ant-descriptions-view">

Error Reason | RC_CMD_ERROR_UNKNOWN: unkown error
-- | --

</div>
</body>
</html>

my evn:
1、vm
2、centos 7
3、Docker version 20.10.16
4、docker-compose version 1.27.2
5、<b>YMIR config=> SERVER_RUNTIME=runc</b>

**Comment by phoenix-xhuang** [comment]
check the executor log under ymir-workplace/sandbox/TaskTypeTraining/<your task>/

**Comment by Sn34931** [comment]
> check the executor log under ymir-workplace/sandbox/TaskTypeTraining//

thanks, the log content is as follows : 

t0000001000005256d3f1653449534	1653449536.268425	1.00	4	169999	[Errno 13] Permission denied: 'nvidia-docker'
cmd exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/command_run_in_out.py", line 95, in wrapper
    ret = f(mir_root=mir_root, src_revs=src_revs, dst_rev=dst_rev, work_dir=work_dir, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mir/commands/training.py", line 356, in run_with_args
    _run_train_cmd(cmd, out_log_path=os.path.join(work_dir_out, mir_settings.EXECUTOR_OUTLOG_NAME))
  File "/usr/local/lib/python3.8/dist-packages/mir/commands/training.py", line 93, in _run_train_cmd
    subprocess.run(cmd, check=True, stdout=f, stderr=f, text=True)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'nvidia-docker'

**Comment by phoenix-xhuang** [comment]
possible issue:
1.nivida-docker was not properly installed, try "nvidia-docker" and fix any issue promoted.
2.run "bash ymir.sh" with sudo (which is not recommended): solution https://www.linuxlinks.com/getting-started-docker-run-docker-without-sudo/

**Comment by Sn34931** [comment]
> possible issue: 1.nivida-docker was not properly installed, try "nvidia-docker" and fix any issue promoted. 2.run "bash ymir.sh" with sudo (which is not recommended): solution https://www.linuxlinks.com/getting-started-docker-run-docker-without-sudo/

thanks, the problem fixed
