### ISSUE TITLE
cmd版数据导入失败

### ISSUE THREAD

**Issue by WellWang-S** [IndustryEssentials/ymir#693]
按照现在的教程，cmd版labels文件放在mir_demo_repo下，但实际操作会报错，repo is dirty
![image](https://user-images.githubusercontent.com/58695014/170406959-79b29212-5374-406b-bc57-a448cee339f8.png)
没有labels文件的话，又识别不到标签，
![image](https://user-images.githubusercontent.com/58695014/170407130-3616b923-5dcd-46d6-8e84-9227f2862d68.png)

**Comment by phoenix-xhuang** [comment]
destination path is: your-mir-repo/.mir/labels.yaml
