### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by zane-x** [IndustryEssentials/ymir#701]
**Describe the bug**

**To Reproduce**
1. git clone the repo
2. checkout to the tag of release-1.0.0
3. run the shell script by "bash ymir.sh start"
4. give me an error message like this screen

![d00b05b68f9ae9385137f18da43bb24](https://user-images.githubusercontent.com/93561716/170654564-3352e7b2-7b00-4948-9b4e-358c5c867672.png)

**Screenshots**

**Environment (please complete the following information):**
 - Server OS: ubuntu:20.04
 - Ymir Version [ release-1.0.0]

**Additional context**

**Comment by phoenix-xhuang** [comment]
update docker-compose to version 1.29.2 or higher
