### ISSUE TITLE
GPU not recognized

### ISSUE THREAD

**Issue by Sn34931** [IndustryEssentials/ymir#705]
**Describe the issue**
GPU not recognized

**To Reproduce**
1、YMIR：
![ymir](https://user-images.githubusercontent.com/101860899/170964743-c5ebc3f3-0471-47b7-95ce-22ee1f06bad8.PNG)

2、Nvidia Info

![nmsi](https://user-images.githubusercontent.com/101860899/170964725-7c261eb0-4b32-4163-bfbc-a33706b05eb8.PNG)
![nver](https://user-images.githubusercontent.com/101860899/170964737-2d40d20b-d6f0-4ee9-a142-d5423b19e14d.PNG)

**Environment (please complete the following information):**
 -  OS: ubuntu:18.04
 - Ymir Version [ release-1.0.0]
 - Docker version 20.10.16, build aa7e414
 - Docker Compose version v2.5.1
 - **Nvidia-docker version:**
 NVIDIA Docker: 2.6.0
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:23 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:28 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

 -

**Comment by Zhang-SJ930104** [comment]
Because the training task needs to occupy more GPU memory, we have set the default that a single GPU will not be available if it occupies more than 30%.
You can try to reduce the GPU memory to less than 20% and try again. 
Thank you for your feedback!

**Comment by Sn34931** [comment]
> Because the training task needs to occupy more GPU memory, we have set the default that a single GPU will not be available if it occupies more than 30%. You can try to reduce the GPU memory to less than 20% and try again. Thank you for your feedback!

thanks!
