### ISSUE TITLE
Permission denied: 'nvidia-docker'

### ISSUE THREAD

**Issue by CatchBeliF-TAT** [IndustryEssentials/ymir#707]
<img width="793" alt="WechatIMG316" src="https://user-images.githubusercontent.com/88470384/171078881-ad9d5028-7340-40ca-8632-79cf9a67ad44.png">

**Comment by CatchBeliF-TAT** [comment]
![WechatIMG319](https://user-images.githubusercontent.com/88470384/171079019-395dc358-04ac-46ab-a5e8-00130c5e3e85.jpeg)

**Comment by Zhang-SJ930104** [comment]
You can check whether you have permission to execute "nvidia-docker run".
It is recommended to check whether the current user has joined the docker group.
Thank you for your feedback!

**Comment by CatchBeliF-TAT** [comment]
Sorry to bother you again! We have followed your suggestions, in addition, we try to temporarily close selinux. The above methods still show ‘ Permission denied: 'nvidia-docker'
We want to ask again what is the problem with our deployment of Ymir？
Looking forward to your reply！

**Comment by CatchBeliF-TAT** [comment]
We can use nvidia-docker to run the container.
<img width="1179" alt="wecom-temp-ea9d60186f6591f34034c5f097ce0234" src="https://user-images.githubusercontent.com/88470384/171318727-3f493566-e914-4695-81cb-63360b8bea65.png">
![image](https://user-images.githubusercontent.com/88470384/171318945-5609e748-ed26-4c96-9e16-d3df41970122.png)

**Comment by CatchBeliF-TAT** [comment]
We have solved the above problems!
Thanks for your great work!

**Comment by Naipeng2001** [comment]
it seems I got a similar problem, how did you solve it?
thanks a lot.
