### ISSUE TITLE
ymir-workplace has no dir named "ymir-sharing", version Ymir-release-1.0.0

### ISSUE THREAD

**Issue by wuyuanmm** [IndustryEssentials/ymir#712]
thanks for your kind to release this funny project! I try to use ymir on my pc,and I success to launch ymir,but when I import voc2012, I don't find  "ymir-sharing", so I create it,and push voc2012 under this dir.  whatever I do, I don't import voc2012 dataset on ymir-gui.  Please help me, thanks!

**Comment by Zhang-SJ930104** [comment]
Path defaults is under the path of your service "ymir-workplace/ymir-sharing".
For detailed operation instructions, you can browse our README.md.
Thank you for your feedback.

**Comment by wuyuanmm** [comment]
thank you for your replay, I read this README.md, but on my situation , I could not find ymir-sharing under ymir-workplace!

**Comment by phoenix-xhuang** [comment]
use ymir-workplace/importing-pic in version 1.0.0
