### ISSUE TITLE
自制镜像相关问题

### ISSUE THREAD

**Issue by CatchBeliF-TAT** [IndustryEssentials/ymir#713]
1.我们成功启动了训练，但未在容器里找到in文件夹，我们想通过in文件夹里的配置去改写我们自己的镜像文件
2.我们想自制YOLOX相关的镜像，但YMIR页面启动训练时默认YOLOV4,darknet的，能方便咨询一下这部分前端后端的代码在哪改写
谢谢！
<img width="806" alt="image" src="https://user-images.githubusercontent.com/88470384/171370687-31b055a6-39d3-4a0d-b643-1491d412ca09.png">
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/88470384/171370704-481c308f-d3c3-43f5-a406-bfdd37411ad6.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/88470384/171371195-cebba6bc-42ee-4579-b52d-f64de0f07466.png">

**Comment by fenrir-z** [comment]
如果有自制镜像（假设 docker image tag 是 docker_image:mine），可以使用下述流程导入 ymir 系统：
1. 使用超级管理员登录，进入镜像管理
2. 在此页面导入 docker_image:mine
3. 其他用户在训练/挖掘/推理任务的启动页面的镜像选择下拉框就可以看到 docker_image:mine

**Comment by phoenix-xhuang** [comment]
in目录对应的是ymir-workplace/sandbox/work_dir/TaskTypeTraining/T0XXXXX(Task_ID)/sub_task/T0XXXXX/in目录，可以先看下这个目录是否存在

**Comment by CatchBeliF-TAT** [comment]
1.想问一下如果我们在这里导入了自制的镜像，但是我们担心上面第三个图中的算法框架仍无法选择，想先了解一下这部分的代码
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/88470384/171374595-ec9d48c3-15e7-42e3-aa6f-1d2cd362db46.png">

2.我们在ymir-workplace/sandbox/work_dir/TaskTypeTraining/T0XXXXX(Task_ID)/sub_task/T0XXXXX底下只有out文件夹，但是目前训练还在进行，out里的文件（log,monitor.txt等)也在持续更新，这是什么原因？

**Comment by phoenix-xhuang** [comment]
1.没有影响，后续这个框架选项会去掉；
2.可以看下ymir-workplace/sandbox/work_dir/TaskTypeTraining/T0XXXXX(Task_ID)/in是否存在

**Comment by phoenix-xhuang** [comment]
关于自制镜像，我们正在封装yolov5为YMIR的训练镜像，这个过程可供参考
https://github.com/IndustryEssentials/ymir-executor/pull/34

**Comment by CatchBeliF-TAT** [comment]
1.十分感谢，我们将参考您提供的自制镜像过程学习！
2.好像不存在ymir-workplace/sandbox/work_dir/TaskTypeTraining/T0XXXXX(Task_ID)/in文件夹
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/88470384/171529577-44462177-a1bc-4c06-8c8d-3306261e45d2.png">

**Comment by phoenix-xhuang** [comment]
上面两级目录，不是在sub_task下面

**Comment by CatchBeliF-TAT** [comment]
您好哦，两级目录下面只有out和sub_task文件夹诶，TaskTypeTraining底下两个文件内部都是只有out和sub_task

**Comment by CatchBeliF-TAT** [comment]
您好，我们这边找到in文件夹了，在镜像industryessentials/executor-det-yolov4-training的容器root底下

**Comment by phoenix-xhuang** [comment]
任务结束后会自动清理，所以镜像外找不到
