### ISSUE TITLE
502 Bad Gateway (nginx/1.21.6)

### ISSUE THREAD

**Issue by lxl0928** [IndustryEssentials/ymir#714]
![image](https://user-images.githubusercontent.com/12816246/171384604-e2bf38b2-c686-4249-aca5-e9dba5fcd596.png)

走docker-compose的方式和走bash ymir.sh  start的方式，都报：502 Bad Gateway

版本：CommitID: 34aa07d94f74eab9a4df59c7bb2bd504b483e617

**Comment by lxl0928** [comment]
error log:

```
2022/06/01 10:29:52 [error] 20#20: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.3.102, server: localhost, request: "POST /api/v1/auth/token HTTP/1.1", upstream: "http://172.168.254.7:80/api/v1/auth/token", host: "10.0.0.251:12001", referrer: "http://10.0.0.251:12001/login?redirect=/home/project"
```

**Comment by phoenix-xhuang** [comment]
后端还没起来，等一两分钟再试

**Comment by lxl0928** [comment]
等了几天，还是报：502 Bad Gateway

**Comment by ringwraith** [comment]
same error, no solutions?

**Comment by phoenix-xhuang** [comment]
docker ps
check the status of backend/redis service
