### ISSUE TITLE
界面不能正常跳转

### ISSUE THREAD

**Issue by amutong** [IndustryEssentials/ymir#715]
一开始自己用test用户安装未成功，后来YMIR平台的技术人员远程帮忙用root用户安装，软件可以正常工作，非常感谢MIR平台的技术人员的支持。
因为是在笔记本上中起的虚拟机，虚拟机中再起的镜像，可能是由于虚拟机的非正常关机(笔记本没电了)，后来出现主界面能进去但不能正常使用的情况，咨询完平台的技术人员，解释可能是权限的问题，后自己重新选用test用户安装(清空了所有镜像，重新下载安装)，安装过程中除“ Found orphan containers (ymir-master_label_redis_1, ymir-master_label_api_1, ymir-master_label_minio_1, ymir-master_label_nginx_1, ymir-master_label_mysql_1, ymir-master_label_celery_worker_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up”外未报其他问题(也不清楚“ Found orphan containers .......这些算不算问题)，情况跟之前的一样，界面能进去，之前创建的示例工程也还在(不明白为什么之前创建的示例工程还在)，但点击这个示例工程，界面不跳到详细页面中，点击界面中“标签管理”按钮，界面依然不能正常调转和显示。

**Comment by amutong** [comment]
<img width="956" alt="捕获3" src="https://user-images.githubusercontent.com/17424367/171403304-c9d49a5a-ee18-4c79-9368-f4063a68ca72.PNG">
<img width="921" alt="捕获2" src="https://user-images.githubusercontent.com/17424367/171403124-d3890d4d-7f85-4404-a95a-36ac1ab72f7b.PNG">
<img width="968" alt="捕获1" src="https://user-images.githubusercontent.com/17424367/171403135-3e489f21-e16b-4e0f-a20d-6bc4343dbb0a.PNG">

**Comment by phoenix-xhuang** [comment]
打开开发者工具，看下前端有没有报错。没有的话，就强制刷新浏览器，不行就再清理下浏览器缓存

**Comment by amutong** [comment]
Exception { name: "NS_ERROR_NOT_AVAILABLE", message: "", result: 2147746065, filename: "http://192.168.18.129:12001/7594.72aae6bc.async.js", lineNumber: 1, columnNumber: 0, data: null, stack: "c@http://192.168.18.129:12001/7594.72aae6bc.async.js:1:22141\nxn/<@http://192.168.18.129:12001/1210.35d8b14f.async.js:1:35085\nuc@http://192.168.18.129:12001/umi.f2500bfd.js:1:1262258\ne[60053]/t.unstable_runWithPriority@http://192.168.18.129:12001/umi.f2500bfd.js:1:1310512\nmo@http://192.168.18.129:12001/umi.f2500bfd.js:1:1202382\noc@http://192.168.18.129:12001/umi.f2500bfd.js:1:1261719\nZu@http://192.168.18.129:12001/umi.f2500bfd.js:1:1252991\nvo/<@http://192.168.18.129:12001/umi.f2500bfd.js:1:1202605\ne[60053]/t.unstable_runWithPriority@http://192.168.18.129:12001/umi.f2500bfd.js:1:1310512\nmo@http://192.168.18.129:12001/umi.f2500bfd.js:1:1202382\nvo@http://192.168.18.129:12001/umi.f2500bfd.js:1:1202550\n_o@http://192.168.18.129:12001/umi.f2500bfd.js:1:1202485\nHu@http://192.168.18.129:12001/umi.f2500bfd.js:1:1250663\nXi@http://192.168.18.129:12001/umi.f2500bfd.js:1:1222231\nt/<@http://192.168.18.129:12001/p__project__detail.a359c2e2.async.js:1:42008\nc@http://192.168.18.129:12001/umi.f2500bfd.js:1:495058\nL/<@http://192.168.18.129:12001/umi.f2500bfd.js:1:496382\nk/</e[t]@http://192.168.18.129:12001/umi.f2500bfd.js:1:495478\nr@http://192.168.18.129:12001/umi.f2500bfd.js:1:157400\ns@http://192.168.18.129:12001/umi.f2500bfd.js:1:157607\nae/<@http://192.168.18.129:12001/umi.f2500bfd.js:1:95139\nr@http://192.168.18.129:12001/umi.f2500bfd.js:1:60970\n" }

**Comment by phoenix-xhuang** [comment]
docker ps
前后端服务有没有正常启动

**Comment by amutong** [comment]
> docker ps 前后端服务有没有正常启动
<img width="985" alt="捕获5" src="https://user-images.githubusercontent.com/17424367/171543722-5ac1cdb0-17f3-4c81-b8f6-663127d112d7.PNG">

**Comment by phoenix-xhuang** [comment]
可能是意外断电，造成工作环境问题，可以清理掉ymir-workplace目录，再重新启动（等待几分钟再打开前端）

**Comment by amutong** [comment]
> 可能是意外断电，造成工作环境问题，可以清理掉ymir-workplace目录，再重新启动（等待几分钟再打开前端）

已清空ymir-workplace目录下的所有文件，一开始显示ymir-master_db_1容器不正常，重启了该容器，但界面依旧有文件，能登录，之前创建的示例工程也没有了 ，无法新建示例工程，标签管理页面无法添加标签

**Comment by amutong** [comment]
先停止了所有容器docker stop ymir-master_label_redis_1  ymir-master_label_minio_1 ymir-master_label_celery_worker_1 ymir-master_label_mysql_1 ymir-master_label_api_1  ymir-master_label_nginx_1 ymir-master_db_1 ymir-master_tensorboard_1 ymir-master_clickhouse_1  ymir-master_redis_1 ymir-master_viz-redis_1 ymir-master_backend_1 ymir-master_web_1，然后删除了ymir-workplace目录下的所有文件(rm -rf *)，再重启上了上述所有容器docker start ymir-master_label_redis_1  ymir-master_label_minio_1 ymir-master_label_celery_worker_1 ymir-master_label_mysql_1 ymir-master_label_api_1  ymir-master_label_nginx_1 ymir-master_db_1 ymir-master_tensorboard_1 ymir-master_clickhouse_1  ymir-master_redis_1 ymir-master_viz-redis_1 ymir-master_backend_1 ymir-master_web_1。之前注册的用户没有了，重新注册了一下用户，新建示例工程，出现了如下的界面：
<img width="631" alt="捕获6" src="https://user-images.githubusercontent.com/17424367/171574727-35184b58-7df5-444c-a75d-fb02dbc17637.PNG">
但点击该示例工程，界面无法正常跳转，标签管理页面无法添加标签

**Comment by phoenix-xhuang** [comment]
不要直接操作docker stop/start。使用建议的docker-compose命令或者bash ymir.sh命令，不然缺乏环境设置
