### ISSUE TITLE
无法从界面正常跳转到标注系统label studio

### ISSUE THREAD

**Issue by xueliang** [IndustryEssentials/ymir#720]
labelstudio已经正确配置并且启动了，docker ps结果正常。
从ymir的web界面，点击数据里面的 “跳转到标注平台”
![image](https://user-images.githubusercontent.com/1107853/172166772-019bad1a-fa7f-4353-8e40-480d89d0207b.png)
能够打开labelstudio，但是设置的token的无效，需要登陆。
登陆后重新点击 “跳转到标注平台”   而且labelstudio里面是空的，无法加载ymir平台上面的数据。
两个系统看起来是独立的。
![image](https://user-images.githubusercontent.com/1107853/172167220-2a797142-6581-41c9-9bfa-ac98ef0ef5a6.png)

**Comment by phoenix-xhuang** [comment]
“设置的token的无效”，这里是什么意思？

**Comment by xueliang** [comment]
> 

在env文件里面设置了token，我理解的应该是利用token可以直接登陆到labelstudio，不用再输入账号了。但设置了token后，点图1的链接，能够打开labelstudio，但是还需要输入账号才能进去。所以我觉得token设置无效。

**Comment by phoenix-xhuang** [comment]
两个系统是独立的。token是为了让YMIR能够发布任务到labelstudio。

设置完成后，可以创建一个标注任务试试，成功的话就是正常运行

**Comment by xueliang** [comment]
> 两个系统是独立的。token是为了让YMIR能够发布任务到labelstudio。
> 
> 设置完成后，可以创建一个标注任务试试，成功的话就是正常运行

谢谢，那请问labelfree也是这样的吗？我试了labelfree，能正常进去了，但是里面的功能只有一个一键标注，但是项目列表是空的。没找到创建project的地方，也没有地方导出token, 导致用ymir.sh启动的时候，提示 “Label free's token is not set, expected format: Bearer xxxxx...”

![image](https://user-images.githubusercontent.com/1107853/172743445-a402b445-f169-4ae4-82f8-08639654e8b5.png)

**Comment by phoenix-xhuang** [comment]
因为默认标注工具是labelfree，所以token是预先填好的，如果需要可以看下：
https://github.com/IndustryEssentials/ymir/blob/master/.env#L34

**Comment by xueliang** [comment]
> 因为默认标注工具是labelfree，所以token是预先填好的，如果需要可以看下： https://github.com/IndustryEssentials/ymir/blob/master/.env#L34

token改了后可以启动了，但是进去之后 跳转到标注平台的link没了

**Comment by phoenix-xhuang** [comment]
把.env文件内容可以贴上来看下

**Comment by ChinaRush** [comment]
我也是无法正常跳转，我提出了issue #647 ,当时问题解决了，我可以正常跳转label-free标注图像，后面我重新拉取ymir项目，完成配置之后，label-free又出现了其他问题，比如 #696 ，还有内部错误, ***.env文件只修改了ip***
![Screenshot from 2022-06-13 15-41-02](https://user-images.githubusercontent.com/39917677/173304055-5ed64968-a951-4576-b406-eadd9c385062.png)

# label tool env
LABEL_TOOL=label_free
# Note format: LABEL_TOOL_HOST_IP=http(s)://(ip)
LABEL_TOOL_HOST_IP=http://0.0.0.0
LABEL_TOOL_HOST_PORT=8763
LABEL_TOOL_HOST_URL=${LABEL_TOOL_HOST_IP}:${LABEL_TOOL_HOST_PORT}
LABEL_TOOL_TOKEN="Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY0ODg3MDQwMiwianRpIjoiZGE2YjI3NmEtNjRmZi00MmI5LTgxZWEtNWQ3NTg5YjEwYTBkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InltaXJAaW50ZWxsaWYuY29tIiwibmJmIjoxNjQ4ODcwNDAyLCJleHAiOjQ4MDI0NzA0MDJ9.knxsip1oXKd8y_J3-epg74ebPsuKiYaOfdtNz6gvLkA"
LABEL_TASK_LOOP_SECONDS=10
LABEL_TOOL_S3_PORT=9099`

**Comment by yance-dev** [comment]
> 
@ChinaRush 问题主要出在这里：
```
LABEL_TOOL_HOST_IP=http://0.0.0.0/
```

正如你所提到的你修改了.env文件只修改了ip。0.0.0.0在这里不会被认为是一个合法的ip。

请使用ifconfig命令查看服务器正常的IP地址，并填充在这里。

**Comment by ChinaRush** [comment]
确实是这个问题，可以正常跳转了

**Comment by ChinaRush** [comment]
label-free 如果有标注完自动保存功能会不会更方便一些，现在好像每张图标注完都要手动submit，才能跳到下一张
