### ISSUE TITLE
非常规操作下，一个不算bug的问题的建议

### ISSUE THREAD

**Issue by huu3301** [IndustryEssentials/ymir#721]
描述：
在项目已有ymir-workplace的前提下（即项目已经有数据），移动整个ymir文件夹到其它路径下再部署（或重命名上一级文件夹），会导致所有新建数据集的预处理任务、标注任务均卡住为0%

步骤：
1、修改ymir上一级文件夹的路径/名字（ymir-workplace下的文件及其文件夹的所有者和权限保持与原来一致）
2、再部署
3、新建数据集预处理任务（如数据集采样）或标注任务

显示错误
ERROR   : [2022-06-07 03:07:11,538] Job "update_monitor_percent_log (trigger: interval[0:00:20], next run at: 2022-06-07 03:07:31 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "ymir_monitor/monitor/utils/crontab_job.py", line 55, in update_monitor_percent_log
    runtime_log_content = PercentLogHandler.parse_percent_log(log_path)
  File "/app/common/common_utils/percent_log_util.py", line 31, in parse_percent_log
    with open(log_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 

查找原因，发现可能是redis数据库里的MONITOR_FINISHED_KEY:v1的raw_log_contents存的是绝对路径导致的。
修改MONITOR_FINISHED_KEY:v1里的值再启动，恢复

ps：感觉不算bug，毕竟是个非常规的部署操作，本来不想提的，一般人不会改名/改路径再启动，但是否redis存相对路径会好点？因为毕竟.env里设置了YMIR_PATH。

**Comment by phoenix-xhuang** [comment]
感谢反馈
