### ISSUE TITLE
可以出一个ymir-gui如何导入自制镜像的文档吗？

### ISSUE THREAD

**Issue by wuyuanmm** [IndustryEssentials/ymir#748]
感觉有很多细节都不明白。自建的私有仓库一直无法导入，dockerhub上的公有仓库也无法导入，wuyuanmm1990/yolov5_docker:1.0。是有一些细节没注意到吗？

**Comment by phoenix-xhuang** [comment]
你好，看了下你的镜像，导入不了是因为这里的文件没有设置
https://github.com/IndustryEssentials/ymir/blob/master/docs/ymir-cmd-container.md#3-%E9%95%9C%E5%83%8F%E8%87%AA%E5%B8%A6%E7%9A%84%E6%96%87%E4%BB%B6

YMIR GUI需要通过这里的约定来确定你的镜像是有哪些功能，可以添加一下

**Comment by wuyuanmm** [comment]
谢谢，确实是这样的，我解决了。

**Comment by ahpu2014** [comment]
朋友我也在自制镜像，yudao遇到这种问题，您遇到过吗
![image](https://github.com/IndustryEssentials/ymir/assets/49829843/a8be3f7f-4a17-4011-923d-8bb7210edfa5)
