### ISSUE TITLE
关于LabelFree标注工具下载数据包出错问题

### ISSUE THREAD

**Issue by CatchBeliF-TAT** [IndustryEssentials/ymir#751]
您好，想问一下超过1000张的任务显示下载超时的解决方案，已经尝试重新拉取下label free的镜像，依旧没有解决。
1）docker-compose -f docker-compose.labelfree.yml pull 
2）bash ymir.sh start 
![WechatIMG402](https://user-images.githubusercontent.com/88470384/173681815-5ee82129-a08c-4237-acbe-6968096658d9.jpeg)
![Uploading WechatIMG648.jpeg…]()

**Comment by CatchBeliF-TAT** [comment]
![WechatIMG648](https://user-images.githubusercontent.com/88470384/173683080-916b57ea-33f8-43b3-ab15-9372c6bcb123.jpeg)

**Comment by liuzz07** [comment]
看镜像是最新的，但是代码似乎没有更新，最新镜像的timeout是60s，建议清空浏览器缓存并强制刷新后重试

**Comment by CatchBeliF-TAT** [comment]
嗯嗯清空浏览器缓存，可以成功下载了，谢谢！
