### ISSUE TITLE
Suggestion: need a better log monitor and log standard levels

### ISSUE THREAD

**Issue by skytodmoon** [IndustryEssentials/ymir#754]
**Describe the issue**
Can't find the log file and check the problem quickly.

if something wrong, we need to find the current log at `ymir-workplace/sandbox/work_dir/TaskTypeTraining/{taskid}/sub_task/t0xxxxxxxx/out/ymir-executor-out.log`

And alos the log file is so large, may be something logs is not very helpful, suggest to add the log level control like `debug/error/info` etc.

**Comment by phoenix-xhuang** [comment]
in next release, the tail N lines of executor-log will be added to tensorboard ui, kind of helpful at debugging.

the log level will be mainly depends on the implementation of docker images, feel free to change the code in ymir-executor repo and send pr.
