### ISSUE TITLE
无法连接到标注平台

### ISSUE THREAD

**Issue by skytodmoon** [IndustryEssentials/ymir#775]
使用数据集，选择菜单栏标注按钮，输入邮箱，点击标注，标注平台获取不到任务，以下是报错。平台刚搭建好，是可用的，后面标注这块就不好使了。尝试了label_studio和label_free同样的现象。
`INFO    : [20220621-01:10:25] invoker_cmd_base.py:83:server_invoke():  request: 
 {'user_id': '0001', 'repo_id': '000023', 'req_type': 1001, 'task_id': 't00000010000232949781655773825', 'task_parameters': '{"dataset_id": 125, "keywords": ["cat", "person"], "extra_url": null, "labellers": ["sunqi@test.com"], "keep_annotations": true, "validation_dataset_id": null, "network": null, "backbone": null, "hyperparameter": null, "model_id": null, "mining_algorithm": null, "top_k": null, "generate_annotations": null, "docker_image": null, "docker_image_id": null}', 'req_create_task': {'task_type': 3, 'labeling': {'dataset_id': 't0000001000023ec62961655706852', 'labeler_accounts': ['sunqi@test.com'], 'in_class_ids': [4, 3], 'project_name': 'label_$sample_project_None_1655706551.9790225_mining_dataset_3', 'export_annotation': True}}} 
 async_mode: True 
 work_dir: /home/qianyan/ymir/ymir/ymir-workplace/sandbox/work_dir/TaskTypeLabel/t00000010000232949781655773825
INFO    : [20220621-01:10:25] percent_log_util.py:65:write_percent_log(): writing task info to /home/qianyan/ymir/ymir/ymir-workplace/sandbox/work_dir/TaskTypeLabel/t00000010000232949781655773825/sub_task/t00000010000232949781655773825/out/monitor.txt
t00000010000232949781655773825  1655773825.686129       0.0     2
INFO    : [20220621-01:10:25] invoker_task_base.py:73:create_subtask_workdir_monitor(): task t00000010000232949781655773825 logging weights:
{'/home/qianyan/ymir/ymir/ymir-workplace/sandbox/work_dir/TaskTypeLabel/t00000010000232949781655773825/sub_task/t00000010000232949781655773825/out/monitor.txt': 1.0}

DEBUG   : [20220621-01:10:25] connectionpool.py:228:_new_conn(): Starting new HTTP connection (1): 127.0.0.1:9098
DEBUG   : [20220621-01:10:25] connectionpool.py:456:_make_request(): http://127.0.0.1:9098 "POST /api/v1/tasks HTTP/1.1" 200 20
INFO    : [20220621-01:10:25] invoker_task_base.py:159:task_invoke(): processing subtask 0
INFO    : [20220621-01:10:25] utils.py:85:wrapper(): |-server_invoke costs 0.01s(0.00m).
INFO    : [20220621-01:10:25] server.py:61:data_manage_request(): task t00000010000232949781655773825 result: 
INFO    : [20220621-01:10:25] invoker_task_labeling.py:25:subtask_invoke_0(): labeling_request: dataset_id: "t0000001000023ec62961655706852"
labeler_accounts: "sunqi@test.com"
in_class_ids: 4
in_class_ids: 3
project_name: "label_$sample_project_None_1655706551.9790225_mining_dataset_3"
export_annotation: true

INFO    : [20220621-01:10:25] label_runner.py:56:start_label_task(): start label task!!!
INFO    : [20220621-01:10:25] utils.py:24:run_command(): starting cmd: 
mir export --root /home/qianyan/ymir/ymir/ymir-workplace/sandbox/0001/000023 --media-location /home/qianyan/ymir/ymir/ymir-workplace/ymir-assets --asset-dir /home/qianyan/ymir/ymir/ymir-workplace/sandbox/work_dir/TaskTypeLabel/t00000010000232949781655773825/sub_task/t00000010000232949781655773825/label_t00000010000232949781655773825/Images --annotation-dir /home/qianyan/ymir/ymir/ymir-workplace/sandbox/work_dir/TaskTypeLabel/t00000010000232949781655773825/sub_task/t00000010000232949781655773825/label_t00000010000232949781655773825/Images --src-revs t0000001000023ec62961655706852@t0000001000023ec62961655706852 --format ls_json -w /home/qianyan/ymir/ymir/ymir-workplace/sandbox/work_dir/TaskTypeLabel/t00000010000232949781655773825/sub_task/t00000010000232949781655773825/export_work_dir --cis cat;person

INFO    : [20220621-01:10:26] utils.py:30:run_command(): run cmd succeed: 
 missing annotations: 0, empty annotations: 0 out of 2 assets
git result: 
 M annotations.mir
 M context.mir
 M keywords.mir
 M metadatas.mir
 M tasks.mir

[exporting-task-1655773826.1539779 43ab7ee] export from t0000001000023ec62961655706852@t0000001000023ec62961655706852
 5 files changed, 17 deletions(-)
command done: exporting-task-1655773826.1539779@exporting-task-1655773826.1539779, return code: 0
|-cmd_run costs 0.14s(0.00m).

INFO    : [20220621-01:10:26] label_free.py:168:run(): start LABELFREE run()
DEBUG   : [20220621-01:10:26] connectionpool.py:228:_new_conn(): Starting new HTTP connection (1): xxxxx:8763
INFO    : [20220621-01:12:36] percent_log_util.py:65:write_percent_log(): writing task info to /home/qianyan/ymir/ymir/ymir-workplace/sandbox/work_dir/TaskTypeLabel/t00000010000232949781655773825/sub_task/t00000010000232949781655773825/out/monitor.txt
t00000010000232949781655773825  1655773956.380800       1.0     4       130603  HTTPConnectionPool(host='xxxxx', port=8763): Max retries exceeded with url: /api/projects (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d4c251bb0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2d4c251bb0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='xxxxxx', port=8763): Max retries exceeded with url: /api/projects (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d4c251bb0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/ymir_controller/controller/label_model/base.py", line 19, in wrapper
    _ret = f(*args, **kwargs)
  File "/app/ymir_controller/controller/label_model/label_free.py", line 169, in run
    project_id = self.create_label_project(project_name, keywords, collaborators, expert_instruction)
  File "/app/ymir_controller/controller/label_model/label_free.py", line 55, in create_label_project
    resp = self._requests.post(url_path=url_path, json_data=data)
  File "/app/ymir_controller/controller/label_model/request_handler.py", line 23, in post
    resp = requests.post(
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='xxxxx', port=8763): Max retries exceeded with url: /api/projects (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d4c251bb0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

INFO    : [20220621-01:12:36] label_runner.py:78:start_label_task(): finish label task!!!`

**Comment by skytodmoon** [comment]
ufw enabled, may be some unknow port need to open. ufw disable is ok.

**Comment by phoenix-xhuang** [comment]
need open label_tool_port in your .env file
