### ISSUE TITLE
关于LabelFree数据标注平台标注完后下载VOC格式的包，其中xml内宽高和对应图片的尺寸对应不上

### ISSUE THREAD

**Issue by CatchBeliF-TAT** [IndustryEssentials/ymir#777]
![image](https://user-images.githubusercontent.com/88470384/174733723-51bdb589-810d-4e82-8964-f66260c5c6cc.png)

**Comment by yance-dev** [comment]
@CatchBeliF-TAT 感谢反馈，我们已经找到问题的触发条件，将在下个版本对这个问题进行修复
