### ISSUE TITLE
公共镜像复制到镜像列表时，一直转圈，日志文件里有错误信息

### ISSUE THREAD

**Issue by zandb2009** [IndustryEssentials/ymir#848]
公共镜像复制到镜像列表时，一直转圈，日志文件里有错误信息

**Desktop (please complete the following information):**
 - OS: ubuntu22.04
 - Docker version 20.10.17, build 100c701
 - Docker Compose version v2.5.1
 - Version ymir-release-1.0.0

ymir_controller.log日志：
INFO    : [20220630-01:40:36] invoker_cmd_base.py:83:server_invoke():  request: 
 {'user_id': '0001', 'repo_id': '000000', 'req_type': 16, 'task_id': 't0000001000000ae49a01656553236', 'singleton_op': 'industryessentials/executor-det-yolov4-training:release-1.1.0'} 
 async_mode: True 
 work_dir: 
INFO    : [20220630-01:40:36] utils.py:24:run_command(): starting cmd: 
docker image inspect industryessentials/executor-det-yolov4-training:release-1.1.0 --format ignore_me

ERROR   : [20220630-01:40:36] utils.py:27:run_command(): run cmd error:
 stderr: docker: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)
 
 stdout: 
INFO    : [20220630-01:40:36] utils.py:24:run_command(): starting cmd: 
docker pull industryessentials/executor-det-yolov4-training:release-1.1.0

ERROR   : [20220630-01:40:36] utils.py:27:run_command(): run cmd error:
 stderr: docker: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)
 
 stdout: 
INFO    : [20220630-01:40:36] utils.py:85:wrapper(): |-server_invoke costs 0.02s(0.00m).
INFO    : [20220630-01:40:36] server.py:61:data_manage_request(): task t0000001000000ae49a01656553236 result: code: 130401
message: "docker: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32\' not found (required by docker)\ndocker: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34\' not found (required by docker)\n"

**Comment by Zhang-SJ930104** [comment]
您检查一下您服务器的glibc的版本，看来应该是找不到glibc_2.32。

**Comment by zandb2009** [comment]
> 您检查一下您服务器的glibc的版本，看来应该是找不到glibc_2.32。

我服务器版本是ubuntu22.04 
ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35

是要换成 ubuntu18.04版本吗？

**Comment by zandb2009** [comment]
更换ubuntu20.04问题没有了。
