### ISSUE TITLE
gpu负载问题

### ISSUE THREAD

**Issue by dapengyinyue** [IndustryEssentials/ymir#888]
env：
  系统： ubuntu 20.04
  显卡：nvidia 2080ti 公版显卡

描述：
  在训练过程中，查看显卡占用信息 。只占用到gpu的一半资源。
 
<img width="561" alt="微信图片_20220705143754" src="https://user-images.githubusercontent.com/30375575/177265325-6d14a8c2-d003-4473-b780-e40672f14628.png">

需求：
  想满负荷GPU资源进行训练，如何配置?

**Comment by phoenix-xhuang** [comment]
batch可以调大一些
