### ISSUE TITLE
运行示例项目到标注这一步的时候，无法下载数据集

### ISSUE THREAD

**Issue by alexw994** [IndustryEssentials/ymir#930]
minio提示文件不存在

![image](https://user-images.githubusercontent.com/37922390/179471301-eeebd97f-e461-436c-aae7-83cd1e61351b.png)

**Comment by yance-dev** [comment]
@alexw994 麻烦提供一下label_worker的容器的日志，或者重新创建一个标注试试

找到对应的容器：
```
docker-compose -f docker-compose.labelfree.yml ps

找到带有worker的容器名，

docker logs -f {name} 
```

**Comment by alexw994** [comment]
@yance-dev 好像是我还没有开始标注，标注完就可以下载了
