### ISSUE TITLE
模型训练报错,失败原因	CMD: 未知错误

### ISSUE THREAD

**Issue by changchun666666** [IndustryEssentials/ymir#949]
系统centos
t通过数据训练模型的时候一直报错,示例代码也一样,失败原因	CMD: 未知错误

**Comment by phoenix-xhuang** [comment]
看下executor.log和controller.log

**Comment by changchun666666** [comment]
executor.log没找到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IndustryEssentials/ymir"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 上午7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IndustryEssentials/ymir] 模型训练报错,失败原因 CMD: 未知错误 (Issue #949)





 
看下executor.log和controller.log

**Comment by changchun666666** [comment]
我用的是虚拟机.是不是因为没有安装nvidia-docker而导致的错误

**Comment by changchun666666** [comment]
``
ERROR   : [20220726-09:41:04] utils.py:27:run_command(): run cmd error:
 stderr: Traceback (most recent call last):
  File "/usr/local/bin/mir", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mir/main.py", line 19, in main
    return cmd.cmd_run()
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/utils.py", line 27, in wrapper
    _ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mir/commands/base.py", line 17, in cmd_run
    return self.run()
  File "/usr/local/lib/python3.8/dist-packages/mir/commands/training.py", line 152, in run
    return CmdTrain.run_with_args(work_dir=self.args.work_dir,
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/command_run_in_out.py", line 157, in wrapper
    raise exc
PermissionError: [Errno 13] Permission denied: 'nvidia-docker'
 
 stdout: training: 1000, validation: 1000
exporting assets
missing annotations: 430, empty annotations: 430 out of 1000 assets
missing annotations: 276, empty annotations: 276 out of 1000 assets
starting train docker container
container config: {'class_names': ['cat', 'person'], 'expected_map': 0.983, 'gpu_count': 0, 'gpu_id': '', 'idle_seconds': 60, 'type': 1, 'task_id': 't0000001000009b43c9a1658828463'}
training with cmd: ['nvidia-docker', 'run', '--rm', '--shm-size=16G', '-v/home/grg/桌面/ymir-master/ymir-workplace/sandbox/work_dir/TaskTypeTraining/t0000001000009b43c9a1658828463/sub_task/t0000001000009b43c9a1658828463/in:/in', '-v/home/grg/桌面/ymir-master/ymir-workplace/sandbox/0001/training_assset_cache:/in/assets:ro', '-v/home/grg/桌面/ymir-master/ymir-workplace/sandbox/work_dir/TaskTypeTraining/t0000001000009b43c9a1658828463/sub_task/t0000001000009b43c9a1658828463/out:/out', '-v/home/grg/桌面/ymir-master/ymir-workplace/ymir-tensorboard-logs/0001/t0000001000009b43c9a1658828463:/out/tensorboard', '--user', '0:0', '--name', 't0000001000009b43c9a1658828463', 'industryessentials/executor-example:latest']
out log path: /home/grg/桌面/ymir-master/ymir-workplace/sandbox/work_dir/TaskTypeTraining/t0000001000009b43c9a1658828463/sub_task/t0000001000009b43c9a1658828463/out/ymir-executor-out.log
git result: 
 M annotations.mir
 M context.mir
 M keywords.mir
 M metadatas.mir
 M tasks.mir

[t0000001000009b43c9a1658828463 f9ba845] task failed
 5 files changed, 6001 deletions(-)
 rewrite annotations.mir (99%)
 rewrite keywords.mir (100%)
 rewrite metadatas.mir (100%)
 rewrite tasks.mir (99%)
|-_commit_error costs 0.05s(0.00m).
command failed: t0000001000009b43c9a1658828463@t0000001000009b43c9a1658828463; exc: [Errno 13] Permission denied: 'nvidia-docker'
trace: cmd exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mir/tools/command_run_in_out.py", line 95, in wrapper
    ret = f(mir_root=mir_root, src_revs=src_revs, dst_rev=dst_rev, work_dir=work_dir, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mir/commands/training.py", line 356, in run_with_args
    _run_train_cmd(cmd, out_log_path=os.path.join(work_dir_out, mir_settings.EXECUTOR_OUTLOG_NAME))
  File "/usr/local/lib/python3.8/dist-packages/mir/commands/training.py", line 93, in _run_train_cmd
    subprocess.run(cmd, check=True, stdout=f, stderr=f, text=True)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'nvidia-docker'


INFO    : [20220726-09:41:04] invoker_task_base.py:177:task_invoke(): subtask failed: subtask_invoke_0
ret: code: 130402
message: "Traceback (most recent call last):\n  File \"/usr/local/bin/mir\", line 8, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.8/dist-packages/mir/main.py\", line 19, in main\n    return cmd.cmd_run()\n  File \"/usr/local/lib/python3.8/dist-packages/mir/tools/utils.py\", line 27, in wrapper\n    _ret = f(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/mir/commands/base.py\", line 17, in cmd_run\n    return self.run()\n  File \"/usr/local/lib/python3.8/dist-packages/mir/commands/training.py\", line 152, in run\n    return CmdTrain.run_with_args(work_dir=self.args.work_dir,\n  File \"/usr/local/lib/python3.8/dist-packages/mir/tools/command_run_in_out.py\", line 157, in wrapper\n    raise exc\nPermissionError: [Errno 13] Permission denied: \'nvidia-docker\'\n"

**Comment by phoenix-xhuang** [comment]
看情况是nvidia-docker没有正确安装或者权限不够导致的
