### ISSUE TITLE
bash ymir.sh start

### ISSUE THREAD

**Issue by zp1018** [IndustryEssentials/ymir#966]
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.ymirnetwork.ipam.config value Additional properties are not allowed ('gateway' was unexpected)
Unsupported config option for services.backend: 'runtime'

**Comment by Zhang-SJ930104** [comment]
Your docker-compose version  unsupport networks and runtime.
You can upgrade docker-compose. The recommended version is 1.29.2
