### ISSUE TITLE
[Backend]tox error

### ISSUE THREAD

**Issue by skytodmoon** [IndustryEssentials/ymir#972]
I want to modify some backend code, but it can't go ahead.
`===================================================== log end =====================================================
ERROR: could not install deps [-rrequirements.txt, -rrequirements-dev.txt]; v = InvocationError('/Users/xxx/Documents/code/ymir/ymir/backend/.tox/python/bin/python -m pip install -rrequirements.txt -rrequirements-dev.txt', 1)
_____________________________________________________ summary _____________________________________________________`

**Comment by fenrir-z** [comment]
tell us about what kind of operations you did

**Comment by skytodmoon** [comment]
> tell us about what kind of operations you did

Just download code and execute tox

**Comment by fenrir-z** [comment]
> > tell us about what kind of operations you did
> 
> Just download code and execute tox

in which dir?

**Comment by skytodmoon** [comment]
> > > tell us about what kind of operations you did
> > 
> > 
> > Just download code and execute tox
> 
> in which dir?

ymir/ymir/backend/

**Comment by fenrir-z** [comment]
seems you are running it on your mac?
how about run it on ubuntu?

**Comment by phoenix-xhuang** [comment]
https://github.com/IndustryEssentials/ymir/wiki/Build-and-deploy-YMIR-on-mac-laptop-(M1-chip)

guidance of how to build from source code on MacOs

**Comment by skytodmoon** [comment]
> seems you are running it on your mac? how about run it on ubuntu?

Greate, I will work on coding with vim instead, hope someday  there will be a much more convienient way. 

> https://github.com/IndustryEssentials/ymir/wiki/Build-and-deploy-YMIR-on-mac-laptop-(M1-chip)
> 
> guidance of how to build from source code on MacOs
Greate, Thanks.
